# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/pi/CyphalDemo/jeroboam_datatypes/actuators/motion/MotionConfig.0.1.uavcan
#
# Generated at:  2022-05-18 08:59:37.982840 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     jeroboam_datatypes.actuators.motion.MotionConfig
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.si.unit.acceleration
import uavcan.si.unit.angular_acceleration
import uavcan.si.unit.angular_velocity
import uavcan.si.unit.length
import uavcan.si.unit.velocity


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class MotionConfig_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 wheel_base:         None | uavcan.si.unit.length.Scalar_1_0 = None,
                 left_wheel_radius:  None | uavcan.si.unit.length.Scalar_1_0 = None,
                 right_wheel_radius: None | uavcan.si.unit.length.Scalar_1_0 = None,
                 maxLinearSpeed:     None | uavcan.si.unit.velocity.Scalar_1_0 = None,
                 maxAngularSpeed:    None | uavcan.si.unit.angular_velocity.Scalar_1_0 = None,
                 maxLinearAccl:      None | uavcan.si.unit.acceleration.Scalar_1_0 = None,
                 maxAngularAccl:     None | uavcan.si.unit.angular_acceleration.Scalar_1_0 = None) -> None:
        """
        jeroboam_datatypes.actuators.motion.MotionConfig.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param wheel_base:         uavcan.si.unit.length.Scalar.1.0 wheel_base
        :param left_wheel_radius:  uavcan.si.unit.length.Scalar.1.0 left_wheel_radius
        :param right_wheel_radius: uavcan.si.unit.length.Scalar.1.0 right_wheel_radius
        :param maxLinearSpeed:     uavcan.si.unit.velocity.Scalar.1.0 maxLinearSpeed
        :param maxAngularSpeed:    uavcan.si.unit.angular_velocity.Scalar.1.0 maxAngularSpeed
        :param maxLinearAccl:      uavcan.si.unit.acceleration.Scalar.1.0 maxLinearAccl
        :param maxAngularAccl:     uavcan.si.unit.angular_acceleration.Scalar.1.0 maxAngularAccl
        """
        self._wheel_base:         uavcan.si.unit.length.Scalar_1_0
        self._left_wheel_radius:  uavcan.si.unit.length.Scalar_1_0
        self._right_wheel_radius: uavcan.si.unit.length.Scalar_1_0
        self._maxLinearSpeed:     uavcan.si.unit.velocity.Scalar_1_0
        self._maxAngularSpeed:    uavcan.si.unit.angular_velocity.Scalar_1_0
        self._maxLinearAccl:      uavcan.si.unit.acceleration.Scalar_1_0
        self._maxAngularAccl:     uavcan.si.unit.angular_acceleration.Scalar_1_0

        if wheel_base is None:
            self.wheel_base = uavcan.si.unit.length.Scalar_1_0()
        elif isinstance(wheel_base, uavcan.si.unit.length.Scalar_1_0):
            self.wheel_base = wheel_base
        else:
            raise ValueError(f'wheel_base: expected uavcan.si.unit.length.Scalar_1_0 '
                             f'got {type(wheel_base).__name__}')

        if left_wheel_radius is None:
            self.left_wheel_radius = uavcan.si.unit.length.Scalar_1_0()
        elif isinstance(left_wheel_radius, uavcan.si.unit.length.Scalar_1_0):
            self.left_wheel_radius = left_wheel_radius
        else:
            raise ValueError(f'left_wheel_radius: expected uavcan.si.unit.length.Scalar_1_0 '
                             f'got {type(left_wheel_radius).__name__}')

        if right_wheel_radius is None:
            self.right_wheel_radius = uavcan.si.unit.length.Scalar_1_0()
        elif isinstance(right_wheel_radius, uavcan.si.unit.length.Scalar_1_0):
            self.right_wheel_radius = right_wheel_radius
        else:
            raise ValueError(f'right_wheel_radius: expected uavcan.si.unit.length.Scalar_1_0 '
                             f'got {type(right_wheel_radius).__name__}')

        if maxLinearSpeed is None:
            self.maxLinearSpeed = uavcan.si.unit.velocity.Scalar_1_0()
        elif isinstance(maxLinearSpeed, uavcan.si.unit.velocity.Scalar_1_0):
            self.maxLinearSpeed = maxLinearSpeed
        else:
            raise ValueError(f'maxLinearSpeed: expected uavcan.si.unit.velocity.Scalar_1_0 '
                             f'got {type(maxLinearSpeed).__name__}')

        if maxAngularSpeed is None:
            self.maxAngularSpeed = uavcan.si.unit.angular_velocity.Scalar_1_0()
        elif isinstance(maxAngularSpeed, uavcan.si.unit.angular_velocity.Scalar_1_0):
            self.maxAngularSpeed = maxAngularSpeed
        else:
            raise ValueError(f'maxAngularSpeed: expected uavcan.si.unit.angular_velocity.Scalar_1_0 '
                             f'got {type(maxAngularSpeed).__name__}')

        if maxLinearAccl is None:
            self.maxLinearAccl = uavcan.si.unit.acceleration.Scalar_1_0()
        elif isinstance(maxLinearAccl, uavcan.si.unit.acceleration.Scalar_1_0):
            self.maxLinearAccl = maxLinearAccl
        else:
            raise ValueError(f'maxLinearAccl: expected uavcan.si.unit.acceleration.Scalar_1_0 '
                             f'got {type(maxLinearAccl).__name__}')

        if maxAngularAccl is None:
            self.maxAngularAccl = uavcan.si.unit.angular_acceleration.Scalar_1_0()
        elif isinstance(maxAngularAccl, uavcan.si.unit.angular_acceleration.Scalar_1_0):
            self.maxAngularAccl = maxAngularAccl
        else:
            raise ValueError(f'maxAngularAccl: expected uavcan.si.unit.angular_acceleration.Scalar_1_0 '
                             f'got {type(maxAngularAccl).__name__}')

    @property
    def wheel_base(self) -> uavcan.si.unit.length.Scalar_1_0:
        """
        uavcan.si.unit.length.Scalar.1.0 wheel_base
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._wheel_base

    @wheel_base.setter
    def wheel_base(self, x: uavcan.si.unit.length.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.length.Scalar_1_0):
            self._wheel_base = x
        else:
            raise ValueError(f'wheel_base: expected uavcan.si.unit.length.Scalar_1_0 got {type(x).__name__}')

    @property
    def left_wheel_radius(self) -> uavcan.si.unit.length.Scalar_1_0:
        """
        uavcan.si.unit.length.Scalar.1.0 left_wheel_radius
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._left_wheel_radius

    @left_wheel_radius.setter
    def left_wheel_radius(self, x: uavcan.si.unit.length.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.length.Scalar_1_0):
            self._left_wheel_radius = x
        else:
            raise ValueError(f'left_wheel_radius: expected uavcan.si.unit.length.Scalar_1_0 got {type(x).__name__}')

    @property
    def right_wheel_radius(self) -> uavcan.si.unit.length.Scalar_1_0:
        """
        uavcan.si.unit.length.Scalar.1.0 right_wheel_radius
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._right_wheel_radius

    @right_wheel_radius.setter
    def right_wheel_radius(self, x: uavcan.si.unit.length.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.length.Scalar_1_0):
            self._right_wheel_radius = x
        else:
            raise ValueError(f'right_wheel_radius: expected uavcan.si.unit.length.Scalar_1_0 got {type(x).__name__}')

    @property
    def maxLinearSpeed(self) -> uavcan.si.unit.velocity.Scalar_1_0:
        """
        uavcan.si.unit.velocity.Scalar.1.0 maxLinearSpeed
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._maxLinearSpeed

    @maxLinearSpeed.setter
    def maxLinearSpeed(self, x: uavcan.si.unit.velocity.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.velocity.Scalar_1_0):
            self._maxLinearSpeed = x
        else:
            raise ValueError(f'maxLinearSpeed: expected uavcan.si.unit.velocity.Scalar_1_0 got {type(x).__name__}')

    @property
    def maxAngularSpeed(self) -> uavcan.si.unit.angular_velocity.Scalar_1_0:
        """
        uavcan.si.unit.angular_velocity.Scalar.1.0 maxAngularSpeed
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._maxAngularSpeed

    @maxAngularSpeed.setter
    def maxAngularSpeed(self, x: uavcan.si.unit.angular_velocity.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.angular_velocity.Scalar_1_0):
            self._maxAngularSpeed = x
        else:
            raise ValueError(f'maxAngularSpeed: expected uavcan.si.unit.angular_velocity.Scalar_1_0 got {type(x).__name__}')

    @property
    def maxLinearAccl(self) -> uavcan.si.unit.acceleration.Scalar_1_0:
        """
        uavcan.si.unit.acceleration.Scalar.1.0 maxLinearAccl
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._maxLinearAccl

    @maxLinearAccl.setter
    def maxLinearAccl(self, x: uavcan.si.unit.acceleration.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.acceleration.Scalar_1_0):
            self._maxLinearAccl = x
        else:
            raise ValueError(f'maxLinearAccl: expected uavcan.si.unit.acceleration.Scalar_1_0 got {type(x).__name__}')

    @property
    def maxAngularAccl(self) -> uavcan.si.unit.angular_acceleration.Scalar_1_0:
        """
        uavcan.si.unit.angular_acceleration.Scalar.1.0 maxAngularAccl
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._maxAngularAccl

    @maxAngularAccl.setter
    def maxAngularAccl(self, x: uavcan.si.unit.angular_acceleration.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.angular_acceleration.Scalar_1_0):
            self._maxAngularAccl = x
        else:
            raise ValueError(f'maxAngularAccl: expected uavcan.si.unit.angular_acceleration.Scalar_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.wheel_base._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.left_wheel_radius._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.right_wheel_radius._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.maxLinearSpeed._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.maxAngularSpeed._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.maxLinearAccl._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.maxAngularAccl._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 224 <= (_ser_.current_bit_length - _base_offset_) <= 224, \
            'Bad serialization of jeroboam_datatypes.actuators.motion.MotionConfig.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> MotionConfig_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "wheel_base"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.si.unit.length.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "left_wheel_radius"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.si.unit.length.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "right_wheel_radius"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.si.unit.length.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f3_ holds the value of "maxLinearSpeed"
        _des_.pad_to_alignment(8)
        _f3_ = uavcan.si.unit.velocity.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f4_ holds the value of "maxAngularSpeed"
        _des_.pad_to_alignment(8)
        _f4_ = uavcan.si.unit.angular_velocity.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f5_ holds the value of "maxLinearAccl"
        _des_.pad_to_alignment(8)
        _f5_ = uavcan.si.unit.acceleration.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f6_ holds the value of "maxAngularAccl"
        _des_.pad_to_alignment(8)
        _f6_ = uavcan.si.unit.angular_acceleration.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = MotionConfig_0_1(
            wheel_base=_f0_,
            left_wheel_radius=_f1_,
            right_wheel_radius=_f2_,
            maxLinearSpeed=_f3_,
            maxAngularSpeed=_f4_,
            maxLinearAccl=_f5_,
            maxAngularAccl=_f6_)
        _des_.pad_to_alignment(8)
        assert 224 <= (_des_.consumed_bit_length - _base_offset_) <= 224, \
            'Bad deserialization of jeroboam_datatypes.actuators.motion.MotionConfig.0.1'
        assert isinstance(self, MotionConfig_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'wheel_base=%s' % self.wheel_base,
            'left_wheel_radius=%s' % self.left_wheel_radius,
            'right_wheel_radius=%s' % self.right_wheel_radius,
            'maxLinearSpeed=%s' % self.maxLinearSpeed,
            'maxAngularSpeed=%s' % self.maxAngularSpeed,
            'maxLinearAccl=%s' % self.maxLinearAccl,
            'maxAngularAccl=%s' % self.maxAngularAccl,
        ])
        return f'jeroboam_datatypes.actuators.motion.MotionConfig.0.1({_o_0_})'

    _EXTENT_BYTES_ = 28

    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8dbNaN0{_)k&u<$=6i!Og{Aki7O#q2TCG?OQkhXT>1c#pqK|#Vza0wtGQ6{sy6Td0z-PO*li7Qn~4xk2&1R}$MTaIw#)*HRS'
        'ksCME6aNAdC*F7++g-<rKnfL+B9FiMX6Ad}d(Shwec#TE_SFB>vti8@u4fU!B2GPihuR*qh!a%8Kyb;l8r_sp?8rD`@7F@65A^eU'
        '`mWBXe&W*#&S!74D6j)sAug3vB1c#h`BVmxuquJ%fp4wXKUM>Oo0qj3Bvlp(1T^%hfe#zw16}MX_I{!Fw7Nj3lo7XM$%MXzhjo$J'
        'WNFpE#+m1~<PF#55Ti%KxdeoMH67EcLw!qdEB3jxJm!}rSep*@Xry5PhKjw#9wP!qZfO{AES&77AdGm0OI}3<Lu+0@<)bEDAU2mI'
        'IYbv{P?bZ4B$dELRnzLJ($R9W%v!~{bu(qG_*}oI)f5qu`Yw&!_Koi0J{4L<{jqBf-j2|4v{0b6YmG7Pp{~v6vvY;H`TXMId|_d('
        'P*_+h<Z>@%^SQ!&zK~zYEiTP1<nvi=&Wdfcr@z7^i?r$^Zs2IugD6##ZP_4pEy?>`4cFlrff2eajF>|ubM?NuNVfS7b4eIPl5kgV'
        's0kv1IC2<Hc#MP;^{WB%;c*+am$1xsN(MbZzk09Z*$|kzIu~-ShF5DLQ12~P3ADN##<s^D60vgZne$pH#>mennZ<<y7xtO#BG_<D'
        'jU^eja#q$ddDPO_J4t{F)D$san#5MQ!}LC6A%_mw9_~7Ol=hbWNR;XCT8+HP<&FCHP5jy@0QCe3Lak=HZ6azFJHU`o$vTFJMP*X='
        'Zpb3jJ*_f2PaNP_-LRp?O4N0^U+y5mrkUM{Jq)v!p2Z!i)Qg$^N@t2QUke+1FibYm#lhIda4Xz56^aA8V+I4JO3`PtdYG`CkoxsD'
        '-H2^r*NbKNGhoakHWgUR=ox~|et{_@On7Wtl7tmem&f9G-ld3_;WT2ahp(i1xXQf1;j(sm7sHjt=(*wyT!mS<b`LV};=gE=@p_{W'
        'v>7w$1isr4OkoZ?;|>S``F&W}fJIo!z{~Ioyb7<u>+l9F!-^U_lB{9X6e6tEiw@p~cj^LR9ZJote$X6!luUknltlQ%<PHc1vxWZ@'
        '=bTo0E@C2YaG%j=Gi1y?$<f)AqtrJY7Lmu{?1U)*>UXpDJNV{AYsb^t&(h*Cw0I>s?^KVkrag8X=9w-v_v3%)@8xvmc60hZ{CJ|%'
        'Bkd8KrOTtuLSAtk?<9|3=u*dz%j@ZmTJC1{Z}97hW=|a#%31$<G)lY8b!Nn7z=a7Y1B2TDun(WY_wXhB3_rjh@JoD56zWpv8xgPm'
        '<|`4er{tZe)zj@SMZBwXR^wX#2Z5H_F2pBsC-XM(kG)ydP;#;2{coO`r|kA;a_C?GcjnD5nTMN97<3uY<raEGPQeZG7NT37<P^M@'
        'karQ??Ifq*!-RZ@=wT;01^<+gA0YamlbnKoPsk4ueb`BU6gGWe{S9IYIpQk~000'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
