# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/thomas/git/CyphalDemo/public_regulated_data_types/reg/udral/service/actuator/common/Feedback.0.1.dsdl
#
# Generated at:  2022-05-06 20:25:55.412402 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.udral.service.actuator.common.Feedback
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import reg.udral.service.common


def _restore_constant(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Feedback_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 heartbeat:         None | reg.udral.service.common.Heartbeat_0_1 = None,
                 demand_factor_pct: None | int | _np_.int8 = None) -> None:
        """
        reg.udral.service.actuator.common.Feedback.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param heartbeat:         reg.udral.service.common.Heartbeat.0.1 heartbeat
        :param demand_factor_pct: saturated int8 demand_factor_pct
        """
        self._heartbeat:         reg.udral.service.common.Heartbeat_0_1
        self._demand_factor_pct: int

        if heartbeat is None:
            self.heartbeat = reg.udral.service.common.Heartbeat_0_1()
        elif isinstance(heartbeat, reg.udral.service.common.Heartbeat_0_1):
            self.heartbeat = heartbeat
        else:
            raise ValueError(f'heartbeat: expected reg.udral.service.common.Heartbeat_0_1 '
                             f'got {type(heartbeat).__name__}')

        self.demand_factor_pct = demand_factor_pct if demand_factor_pct is not None else 0  # type: ignore

    @property
    def heartbeat(self) -> reg.udral.service.common.Heartbeat_0_1:
        """
        reg.udral.service.common.Heartbeat.0.1 heartbeat
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._heartbeat

    @heartbeat.setter
    def heartbeat(self, x: reg.udral.service.common.Heartbeat_0_1) -> None:
        if isinstance(x, reg.udral.service.common.Heartbeat_0_1):
            self._heartbeat = x
        else:
            raise ValueError(f'heartbeat: expected reg.udral.service.common.Heartbeat_0_1 got {type(x).__name__}')

    @property
    def demand_factor_pct(self) -> int:
        """
        saturated int8 demand_factor_pct
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._demand_factor_pct

    @demand_factor_pct.setter
    def demand_factor_pct(self, x: int | _np_.int8) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if -128 <= x <= 127:
            self._demand_factor_pct = x
        else:
            raise ValueError(f'demand_factor_pct: value {x} is not in [-128, 127]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.heartbeat._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.add_aligned_i8(max(min(self.demand_factor_pct, 127), -128))
        _ser_.pad_to_alignment(8)
        assert 24 <= (_ser_.current_bit_length - _base_offset_) <= 24, \
            'Bad serialization of reg.udral.service.actuator.common.Feedback.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> Feedback_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "heartbeat"
        _des_.pad_to_alignment(8)
        _f0_ = reg.udral.service.common.Heartbeat_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "demand_factor_pct"
        _f1_ = _des_.fetch_aligned_i8()
        self = Feedback_0_1(
            heartbeat=_f0_,
            demand_factor_pct=_f1_)
        _des_.pad_to_alignment(8)
        assert 24 <= (_des_.consumed_bit_length - _base_offset_) <= 24, \
            'Bad deserialization of reg.udral.service.actuator.common.Feedback.0.1'
        assert isinstance(self, Feedback_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'heartbeat=%s' % self.heartbeat,
            'demand_factor_pct=%s' % self.demand_factor_pct,
        ])
        return f'reg.udral.service.actuator.common.Feedback.0.1({_o_0_})'

    _EXTENT_BYTES_ = 63

    _MODEL_: _pydsdl_.DelimitedType = _restore_constant(
        'ABzY8Q-pP50{`t=TaO&ab>5{Ua@o34v}h)_qqZGeyXI~$my{@5N+K_pl(boLN$gS<?LZmSOxH}+vZuRUT|K+2Fo6|Vi3oHM+Ux*E'
        'fV{>If;<GU0sRF31i$#*4}LNdKraFEox03@mSljud4QQy(_LM4>eM;kxm5q)$$x4u&Y4g3a();WaS}BOt|Uw3hpd_KsL{&0c~(fx'
        '>+0DnJds^A<6DP0uOHM)AJu<dFILAJGEKRv#a#95u2yABmx_;ed8(1JE{6Dq;+?3B6-y#a(~~V8F?44-QxRtBW@+>`=W&y@?$p&n'
        'qsLVtvy?_Y@g3KGP;bp`&Hr8fQC&UVU|K8LEHy9c4=~M)HS~Mc)l+Xvp2P#jf=0|VYiQzDoUj)~P<>^RPsiT7oGIPpOxNNW@tkKx'
        'oWk_tCHMT<M;d8|vsk9QD2^Iw){=5XJ0W{m(&_ioLUvLfZ>E}exEhuG(~YLojfAHiE$XdfSa6FKy3x&IEO@CpbJGt*k3}1}cb#rQ'
        '%JU!BJ9YKBMxj|6GZhaHbgyh;ZBO-BQi6jg8*$dEtGOCiPge^YSxV37J`)hgIoFD|j)_&VwlznCi&xz^yVtH>y;+M(xBuhV+}tg}'
        '!z4>PE1Iirh><i8vv$~(sqC^O%(H#2!WQNzySau&L;+ZrEtVvQ%V9SwbXb(l;;_)XTZByUu-KQnC3qalRA-^a@MgY{WDxEPo|<bt'
        'E@Ug=p)A6jsXOS7W!u@%&f4uL*d2_k1=C@ig=t39<$0#`(8!kQLS$tUhgv~fLa9RrcG8f4zm$+0Pc^M-_tyIMmCN6af?$2XcGzWy'
        'p`wo9o|)?;Pi%k4x>;$T)UwM%tcM>+J9Uw8p4&w&wljqrteYo%+4iI%n><WmU09CJf@YT4=dzqDre)d*-R!h(Ra&VOJi$~PLd{jy'
        ';xR0{SOT~23rVs{$Hcj8AL=gz!o<EnhBRf^;;f({jTz8@JxL~QCM<N8Q(thX_cL`T1TM&))Q15K2-=sxP-xj1CQx2DT}ZK5#!6c}'
        '*LF`Jj6%>jSS*<e&5I47!DvsUHY<{C$hB{PVHZEFLwk?eS{&98hh(K-jO4=7L$8Nsc1)DoMMpKz&so8jyruGk98#i{jo9hJ4kLAC'
        'iMI=JxjNZa#2S<t_uqDH+^^=(*JL3@69)3F8CLX`x1SSEi^zh$I&UqgZ#PX&OMnRCL!&ML31xOE%@o<wVEc{gU`rWkF7!E5F;~%u'
        'Vp<Uw)XU8|s_R2ShY@MnlDUz3Iy~d}4#R*2jaisZF>kXn(QaHb;iyizsUTwM_-)gYjHRwXn_wR@fllNJrq{`#-$}A!+P-~R@Cd>e'
        'SKTg%Kd<I5JdU`pZojks&eba<?h^p4_X$GWwJ8Pw`NAB#Bw=VD3=u2?iMZjYU8ZKwL$}N{Lq|e6`w&ZEC@sNAGl2gEBw9pAL5114'
        'QIJ@MXrPTvNTS4?3f<a#A7%&)jbT05D~piWJ-yEz9J=+8Z3ZJ-U4)AybC^VoISumwgx##mhjEwKB5aIhyA1#(@WO8T3H*R$_<o{A'
        '9(AH+0@`K<dpEmQroeS09*7{`2beFBvhcC>$Jo)dV+`1uH!F1pNoHk%MLXr=JqNj1K3sl+ClfFIW$LsK{1+j-BM+#*;som0B9B*s'
        'vqTFcgt8b?`1jX$wl}xmnNX>VeU;+X>7hua(LA)#5UJK{;uZ02@rKwD+u{T9-4gyf=70|@o5%IN>bXW+9`Lw9yfkE7Z&#-pMOLa7'
        '$Bl$HU|yoGP7q0Cv#w6wM6h;nlde91_n%*dcNQ6iUdJ^k1I|3rk-Dyejl&!`d4+egy81$1HeoFdKy8`O%!8<i9>8TpP9})KTuvSs'
        '(FQVg^<p1Mqw~>PL?~Em3LZ{31S`NJDL}(NcMoRs>*E%sR3Cz^xx-w_!Z{0TwLl@a6=oM%kI95JWdhvrTVeLpfy&T+E%ud!9M(Ev'
        'xCapO4}$eLSzQ9B1ieUynelUDggvOZMIo4AVSISlNwQ`?60x=u1y>QQ9u6rctV^pbNle^<>(H%z=<2>vo3bb=Uhyj<To@GvmPJ7@'
        '34*m+#+=EglL*?(ab(m~D~9mT*oe2TzRit`cVL!H0!|ZDu$040tW{00VA(UsRUq1djGBjVmYC6ii{Qh?VZ-8(l&0?|SW;w!=omG&'
        'hKP%#{6)@M{LSEqA?RuFVbcjn8<I8G&BWv@C|(VMFg&+1^f`wMcf$=YdllXty0<d+IpRVTMIn7=>cqsvVgGYC9Q#aO2<Z1OhrWYP'
        'Z@ly5g}@JbcX;q~<GdVoVfqkv!(F!-cOUHn#Pt8h%wx&YKRLRk=N{wf31yi4Jbbt*%Ix%|2*O93WctiOut|ZLiGtxsdXx(QDUG`#'
        'Lsb0;AE7BzNYxYr9HnKq2_t~b7yz27&2Z{T)*8b!MEZe8F~WczQ!*ph=X^Xm2|1cPIVX<LJ};BPcveI*6rB@5!AlpJLdY@V+Y!I('
        '7C|&Ykaa}X=PTzCJbqA=M8mCkAvakeF&ez84f_qWrf~F%1d*7fm{@%+eD}lUz@`Z%(Xj)#G>&q_kxa&b<ycHWGuU7b@w^_+XQm}B'
        '5hcaV1kUs8J}Vex&+vqL{C{0Nb6M(Z=Kn75r_R+AjV!OLaMmEjVYit<U~sk9;mPHPMshbyNS~?U5={#UTU?93t)9QhV#;bJI*Grh'
        'yW3@wKy$|Lip&34FK!*XUo@))ICL{Yy|qv_u}(y+Xi|e6P~!wu7Z69#pj-3w+}!=GV~##y$Ju(){eOz+6Zf}{yXz;2&fni!aQ9CV'
        'UAVs$IQq1s&p7(5qt7||yrVBTddkrk9X;*n=Nx^>(KC*I-qEv;{(+-^=;#+5{i35^a`cZJec92_(Jwpt6-U47=pQ@!HAlbh=qrvc'
        'I=bZOHyl0Z=(3|Ljz*5II(pvGHAgQvdePBW9evHwOOC$o=r<kxmZNVt`lh3Q;^?0``e%;5<><E^eb>?3jtWN)9R0-6pE&w6M?ZD+'
        'myZ6*(cd`wnWfhk=3V2gZ!G%8H+|z>-?;4?!Z!|l;}hTbiEsSOH$L@^U;4(ceB(F1@tJFsRY3Va#bk(#-L<C4D}(B!8kGDliPv#$'
        'TE+0ilJ#0FjZ&oJRBlAlVJn35TXWNDjWe=TSDbSbJv^!1zHxnXd;J<7sLm4-o5F8OQ6yl`CrSjK1nyiRcwKbK>e58&^Ekzeh4m}n'
        '+1$OcL)DAwr|V%$A(}O=2w88JQ)<6&GPlxXZwPmh=ebaLz#~shkZfvojB17G(MGCJD(-7_fO`skkz7$G7>wrWZIyM0Gj+;uF`Em_'
        'lND1#^HL}#7QFU2<%5m&_ik<8*rxUNZXLA>wl}m2^44S31oDS5?<hu<1XI01f5^!cMjZDsx5eSml<wJd_8+VI;qqN#|9hkC7o|x&'
        ';%O<i=f6z*1tPl=!{tOh<fv>~#9(W0etvFF{LkKTkiBE{bBcbRrJpa-&sq9;g?^|cR*LpL(b*P4+*uTf=!#TiA{XDUj$3Pkzb1RD'
        'tLLr7A&oshNMyw!C9M+UtT&O8Py#kswW|xr)D&zC^WkRORdcWrZk<TJ%0$Z?i+53iq*{upg2sI4u8$>rkg~KKkcg(19~5sVHbLb>'
        '*)aXX5QSbD)@T=+z-&h+K<M>$Mn&4<4aBHI>%4elb#;G#KT6ns)XG%KlO*DCx!P*0Rm~6d>e{QT7cNF?7cX2Gd!o%))X93Qan>rS'
        'ID1VtDGpuj@>sIf^|&Vy03J3rq-r5RP^;@3jSH`tfmYU{JZ@7}%4o}_TKtvx8@vA>i68bOlzaWwKa9mC;ztyYh#zk)hzI!oKKS^3'
        '@KK82jd|eX!uiwLUU9*K-6y91nd|Gf8#mv(d~I`MoiMv`^Xks#4XXTB+EkQWCgSTI<X|RK32&_?xhX{G%-JP~i<vSwuFSE6wc@2g'
        'Wy%zWF*IdENBA9!isHY-%X>c{Wc=^Fj|uxeIs*HI5{1yBtX}LNYL3?LEbRT(ohbB?d}iqfTo&*$FznDAv@z}b8Xz2W9H|Hy<T59W'
        'gUXOk*7|2UzA!i|2c)7Dp`1T2805p<%!UA|sqwijpz{KJO^9U^&nby}zryPuibF2V0g&OM;1r=~?sMp6^1f`MYK3`x-HHWnmX#vs'
        'E!mc>KAhVjqHtCYJn`UI(rasaV=1p$nmt*WT}tCa=U}F$_E6;g;ZVN#(ngk2tva2WcvdHE-l=#>=krrX`*;$#J^mKrciRxm>rg;m'
        'P>&bT<Auo{{Sju|_u;n~oZVl#{ZotzH$8H0<KIOH`(D|r1r=eHIShnmll?x@LCp<+-n5MVqqXZ!iN1(>xILqG6UI@no#{TJm~yXs'
        'AL0?JqT@Bx<*>+%)+4|%u`Xikrir~+&>z;<xXZ%Y&-frwxNB{ij@Kt|KZK)TRJq0s)$>-`BG#BDk}>U5>`{+oN=wzL-I?z@j05<o'
        'm{XmrK}GXSHS(6(`|n}z|H2feQvE@2(>Cb*$ceGb4rI6N8taQGqRz?MC`K))xD#Fnv=Bhy=DC%%^XI=tNM@=;bVA)jc9bz}C7s34'
        '*>7l4G4zSatbN(ZmfA>sd7emHQPSq!2Nu7HD6qrKv$LME=ek9i-m%FG37Z}ryyY;^W?R%V$40i&Z(pCVl|kcO{0TULW<nJ-`eW`4'
        '#kIsCq-k$)f5HKVvpg&qZNClO`!V{zktaH{_n+j6{{5kzs9NwG*KkUw{EI--eA2%fp9JoN?1&Wuk^_aFg4-FHr|g<ARCDC6_RN?-'
        'T<4jzNv_+6DA=UK784N<%y0sft*T(lo#+aBvx6nYh~MiE?>j|-IW3;JZa~1IIBhGpMaJdnQ`4@{s~r?!o69TCp)OClg<#YzxD$5S'
        '&j_tP<Vt3WU};<*2EsJUfqy2e99|-DQNd|v_Em}Tg*}Eh+52Z~s`<0`FKEs17kdv#r+&0GKMMHP4-Dr73&;tq*Eow#X9u0UvlzW>'
        'eS~;gJR@GP6_ztbW&cl_y!UhJUhe$@q_4DlpW<J2qJabo`&M87Y`!|vh}|o7ssUI<4CvlO8-$}F(Cnf`vuT2yBD7&4gp?Q!`|Ho|'
        'Q2k_w=UmHKrQ$obko(qHl0^bFf}0Z$!2G0}wbBl8_w2FhPB{8sQ4EC3aVP))'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
