# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2022-05-06 20:35:07.382036 UTC
# Namespace:     uavcan.si.unit

# There are no data types in this namespace. There may be data types in nested namespaces.
