# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2022-05-18 08:59:36.868706 UTC
# Namespace:     jeroboam_datatypes.sensors

from jeroboam_datatypes.sensors.resistance_0_1 import resistance_0_1 as resistance_0_1

# Convenience aliases of the newest minor versions known at the time of code generation.
resistance_0 = resistance_0_1
