# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/pi/CyphalDemo/public_regulated_data_types/reg/udral/physics/time/TAI64.0.1.dsdl
#
# Generated at:  2022-05-06 20:34:32.625887 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.udral.physics.time.TAI64
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class TAI64_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 tai64n: None | int | _np_.int64 = None) -> None:
        """
        reg.udral.physics.time.TAI64.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param tai64n: saturated int64 tai64n
        """
        self._tai64n: int

        self.tai64n = tai64n if tai64n is not None else 0  # type: ignore

    @property
    def tai64n(self) -> int:
        """
        saturated int64 tai64n
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._tai64n

    @tai64n.setter
    def tai64n(self, x: int | _np_.int64) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if -9223372036854775808 <= x <= 9223372036854775807:
            self._tai64n = x
        else:
            raise ValueError(f'tai64n: value {x} is not in [-9223372036854775808, 9223372036854775807]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_aligned_i64(max(min(self.tai64n, 9223372036854775807), -9223372036854775808))
        _ser_.pad_to_alignment(8)
        assert 64 <= (_ser_.current_bit_length - _base_offset_) <= 64, \
            'Bad serialization of reg.udral.physics.time.TAI64.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> TAI64_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "tai64n"
        _f0_ = _des_.fetch_aligned_i64()
        self = TAI64_0_1(
            tai64n=_f0_)
        _des_.pad_to_alignment(8)
        assert 64 <= (_des_.consumed_bit_length - _base_offset_) <= 64, \
            'Bad deserialization of reg.udral.physics.time.TAI64.0.1'
        assert isinstance(self, TAI64_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'tai64n=%s' % self.tai64n,
        ])
        return f'reg.udral.physics.time.TAI64.0.1({_o_0_})'

    _EXTENT_BYTES_ = 8

    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8T84FE0{@*=-)me&6i!Xk)U8%ROJ5WmUnGU*W|NkL#FxZsp~R-q1QAOe=FXhmJ23aobbf5JLcu;L76ueD`uBQfb~hVa@}SFw'
        'y?5sP_|A8}IrGcazwGit`NdDoSU907>cC2-<j<^DP*JX1qn-4S;)loH2JVA}ld*wxmhQezuhME<q8)2-{}T(tDhSI|Wty>*+*Mw-'
        'P@U{Q-g=PYbvgp;r0!C)5SPE7zMrLog@Y@<rPnFmpv-$K>)^qq=jk#;=SC?mJ(8fr97&G~<{9-F-evB_%2s+gLW`ASIqX0@?mP^^'
        '{=29fw3ePK=!U*Y2YVQrGv{fm1*GP7ymK@QlijL^xc4M)<#K*a-=%n)I?p=6thgBH_fR)W@tS9H>p_>|RVp-3aqn5jI_-e#PCO@v'
        '=kJbyV#a|WPIer~#?E$st-pcKNx#2ao*xOaTcuF5c<Tavv>s2I@+vi?S#em70AqnO4<fyZH|ap0f}loQPo+qQafLb^EC<|BKn+8%'
        'aXJ4fS*Q5^5o+M{D6gI&Iak&Zd!uvH-!n4B-ovqJnEDD@o#MwP)Jk%SY6vRln>WR!xQNTxxFVCBVImX^m!*>8%_5enUu{&mdC6xk'
        'Z_$Q1#AKoKxtk-&A-!on`{D1!g@xlO&7^o9k{pL9R)Zp|jrYdwuCH@jjZNkCIu?W6uNVHS#<%KjMZOK%0~uJ|65jxs(6HO<ksOhf'
        'E;=&MmYhIq9NG7}l`jI2EF0S~k1A&BUh(C@W{gB$+#(j3S}U+-lBh8F(+(yHN~?)<M8H6z90_wJm<YB+AbLP{Hg-0*?r&^w_lZF@'
        'Yea;r*~&5@CuUq@a%V7@?1q@Y>tf(7>+t+$iyHh(fNrw<Qj-Q-VslQSU<B$s=FsYZkPs~rGhO50WM~P)>Z>U=OgT-Q0WJp;9AU^I'
        'N-jHC7yuH%p(2lhMR!YtbUZjWt*3YuYEU6^B>gxOpo4c(K*pXM!L^yD&*W$xTI9CMjoF_xd)j8)WnJMMPw{z?eOwe|^CvVba4fQt'
        'Ibj5a<RwRK+8Ox;GQuh2icIGLaT7=EhAwi*zqJDGLf>i_%C5_?;goT&#yRCC+Bq^i#5JILpg7L0F=al^In=#rY(gY5lgpXcfahKX'
        'hht_|%_ioVE`33?{SUYt8kGPuTx@_U{Xeiuly{KbpChY!dA8LG&-LfCDLkKoc!d4i-zk3ZrS#vF?_>O&&f&O7wMmg&7Q~I)TH~<6'
        '8Sw;%56<{3^rt9m6snz1^J|nh5^suTFMf2yL_Q(!7&Tw#-NT?z7~{8hF~W$c0O^mkda(DWtMNKBlR)X<dZ@A7R(AQKz!!F!UzYP_'
        'fhx=1Jqo8LpF_Oy4nytgP*?u|RYsOgeFp#l'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
