# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/pi/CyphalDemo/public_regulated_data_types/reg/udral/physics/kinematics/geodetic/State.0.1.dsdl
#
# Generated at:  2022-05-06 20:34:36.132976 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.udral.physics.kinematics.geodetic.State
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import reg.udral.physics.kinematics.cartesian
import reg.udral.physics.kinematics.geodetic


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class State_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 pose:  None | reg.udral.physics.kinematics.geodetic.Pose_0_1 = None,
                 twist: None | reg.udral.physics.kinematics.cartesian.Twist_0_1 = None) -> None:
        """
        reg.udral.physics.kinematics.geodetic.State.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param pose:  reg.udral.physics.kinematics.geodetic.Pose.0.1 pose
        :param twist: reg.udral.physics.kinematics.cartesian.Twist.0.1 twist
        """
        self._pose:  reg.udral.physics.kinematics.geodetic.Pose_0_1
        self._twist: reg.udral.physics.kinematics.cartesian.Twist_0_1

        if pose is None:
            self.pose = reg.udral.physics.kinematics.geodetic.Pose_0_1()
        elif isinstance(pose, reg.udral.physics.kinematics.geodetic.Pose_0_1):
            self.pose = pose
        else:
            raise ValueError(f'pose: expected reg.udral.physics.kinematics.geodetic.Pose_0_1 '
                             f'got {type(pose).__name__}')

        if twist is None:
            self.twist = reg.udral.physics.kinematics.cartesian.Twist_0_1()
        elif isinstance(twist, reg.udral.physics.kinematics.cartesian.Twist_0_1):
            self.twist = twist
        else:
            raise ValueError(f'twist: expected reg.udral.physics.kinematics.cartesian.Twist_0_1 '
                             f'got {type(twist).__name__}')

    @property
    def pose(self) -> reg.udral.physics.kinematics.geodetic.Pose_0_1:
        """
        reg.udral.physics.kinematics.geodetic.Pose.0.1 pose
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._pose

    @pose.setter
    def pose(self, x: reg.udral.physics.kinematics.geodetic.Pose_0_1) -> None:
        if isinstance(x, reg.udral.physics.kinematics.geodetic.Pose_0_1):
            self._pose = x
        else:
            raise ValueError(f'pose: expected reg.udral.physics.kinematics.geodetic.Pose_0_1 got {type(x).__name__}')

    @property
    def twist(self) -> reg.udral.physics.kinematics.cartesian.Twist_0_1:
        """
        reg.udral.physics.kinematics.cartesian.Twist.0.1 twist
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._twist

    @twist.setter
    def twist(self, x: reg.udral.physics.kinematics.cartesian.Twist_0_1) -> None:
        if isinstance(x, reg.udral.physics.kinematics.cartesian.Twist_0_1):
            self._twist = x
        else:
            raise ValueError(f'twist: expected reg.udral.physics.kinematics.cartesian.Twist_0_1 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.pose._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.twist._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 512 <= (_ser_.current_bit_length - _base_offset_) <= 512, \
            'Bad serialization of reg.udral.physics.kinematics.geodetic.State.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> State_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "pose"
        _des_.pad_to_alignment(8)
        _f0_ = reg.udral.physics.kinematics.geodetic.Pose_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "twist"
        _des_.pad_to_alignment(8)
        _f1_ = reg.udral.physics.kinematics.cartesian.Twist_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = State_0_1(
            pose=_f0_,
            twist=_f1_)
        _des_.pad_to_alignment(8)
        assert 512 <= (_des_.consumed_bit_length - _base_offset_) <= 512, \
            'Bad deserialization of reg.udral.physics.kinematics.geodetic.State.0.1'
        assert isinstance(self, State_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'pose=%s' % self.pose,
            'twist=%s' % self.twist,
        ])
        return f'reg.udral.physics.kinematics.geodetic.State.0.1({_o_0_})'

    _EXTENT_BYTES_ = 64

    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8T!wXG0{`utU2ogg8OLSGl4V<Q<d-C_lO{}>CQjlgdKZ<gTe@Uf047=11Z~!?lPHPyp(~LZNhNlN4r=#;1RyX1<$wVD0{sZR'
        ')b4sUV0Y<dF`&&h48t&N2(SU&IpqIH4r3?jR_tP>0sDC<l85Jz`u(4W=ONu6|J56pBi@gFsJq!RTkTBER18&at8dGVwvwqe^-fne'
        'RZDU0UDqw6*R*<ua$~crxbM3s-gVz`m+g2>lRI?%DMMMy^je18&UDG9sW#2bTdJmXWQ)0Lir!MFm$`1qthHqAmSUKyuDK*)PrM5M'
        'eOHP|W500Ub?xbzY*~id=vj*CzDbX>Ll1{rxpw@bs<d09o=w$SvL)9n)?E_yKO}Mc<g<13nr_nFCdef35=qf+kTlwv-_qi#XKhi{'
        'tS2?O(-^yk+EFd_79Hc{#kMY6k6wZ4T0^yJZADwNh%23=<8I2PRqN2hy5y+6_Zr`w?Up%D*Ii+&*vbC6`-*EX)J#j(TC&mF+Rz=^'
        'PDftTRIArw2VOPgrbRE3NiW_-__U3irLjmPSE*LY)k3aN6wCQSu2jj2xne0_Ddr26Lavf67E0wxRm@hh)Ryuku~@8D%cZJV%~gt('
        'vY2K2<jdKLn9b(JQbDYgvn8=wDv9MnzEUoW6){)Im5SLS`?OHX6$@g%Sf<Sv3;A3jUlzqGUCfDeW3fmNL4UJ_QlV1Hm8)VoOOKYz'
        'mMY~^DVG=X*-ANIEETKSY&BaDtA#w>xtOicgNdcASfm>j3RT)RJ6a)MDATR-`Fyn~=E@~8E0#*t0zGQJKu1f5NQW-w%lT|ES1eZO'
        ';Av+Iw6~R<n62ij`D#@ZbNN!1_C1>~=fq+zUleJ(Wzl6Pzt^DOpJbbUQ~c9BUTf)1dWPRH<d!OHZ?X+WU%6xOPDtm-Ns=LF?vN}g'
        'gqPsIzXX$QU0d_70TFjP{UhRqo_wn*YZ+6`^e7=2pP9^SYD>A^l-si5V?HKDIOgG1{2yG!ct^1mgI&Q0{Xn+ow*-+|W7CgR@3`a@'
        'BAHY+TT0hZnlv7@+`INnZB^Y+TD7ijST(ifUbSayrrtA}3SH4wYF(L%qCLS(TWwH5qya+RxW+zxpNjC<8454aStN{hRo9+6zu6^n'
        '`-0NZU3-7G*J!KF8jTaZHap%ZGEq5A_+KWvqe*uhXJ07#A!OK|AAPAZxlA_00)%TZ-JY)z*`)n46wP80<CfY~+`B|1*Qty&+O*|k'
        'Jf4hnoo;9amt8ycE!Dd0EnlaLh%9!jrgvRi*r^e7v(wP&uxL-N&|%VO#bUyDyNV%Ox-p7RiCUAWG%%B{z5ANnYN^`VV;hkkTYI(F'
        'ro-F}uB9#9lG{DS{iVAsopa0vO&_{`L#~wUHRy0Vs>VVeb>t1^OtA1r&oygX8e{uK94QJLV|L7u#<3h{cHEH?uoGCH#QI4rPhtHu'
        'vy+aL!tyR=Q;sylY|@c-<MTB3pJjHJBh4{8<w*0)PB_v6w%ddD_cFWSNc)(bbEHLP(~k5UvonsggyZZ-I|p#Q=b247(m}L$h}ozk'
        '2{`^?W)C^i5oQlM(hJN!??^|PJ>W<$GP~cAjxoFBNXMCd&XJaxU38=q%<glflg#dQq*Ki9aikUW_cXKfj+8;a&oDddNLlnh$LwxL'
        '%3~Y_oR1>LQ(|`7k;)iX1?N}9_^LQxXEDyNF&lTJuVcI~F&lHFZ(!Wt#Q8jj@n7=4H_}a50=ofw2lgK92e2Q)egu0T_5tie-(E?M'
        '!CB<aGIvDoT;k46?hx*5aOVzp?s4Y>?tI9dkGON6I}f<?5KfO~Zpubi*1Vh=pEb;epKHi%YZ&LO3o1+fnu^d+tlNsB2^LX=wocVX'
        '=qR!#n2Id4m0L<%SiW-o@(F>aiQXow-X>j^&<gsh_mQkwil)gKf$1X4HU)kpL2l@Dk!?g9$xvlh$PLDPg&ZL-le6Ua<b033dY8O*'
        'mE0t6ER!FQH^~o4jnwTJRZN=Ld$~0eUq8F1>N?7=X|lvKY}cOga%`%Sxsgs1LN(F;&3CYo;N8&BGjmqpY1fJ{jQ%U$5P8otQ#WX*'
        'b)%&if@%s)LhlLaIno7s=qB-py+K!aTTnIP=i=(OF9<YW?w|oveOvL`ZOfZ_4`+<-X7W2K*0}Pc9zCVBZPvhf*`OhdW+1G$^whD$'
        '-6bk%dwNK8Vhm;T_Rur7Na>#Qy2c`#wyh@HlfER=$ieQdp3>Sw|DgZeY0Dq`>wm)4ne?SG`dxdMrZ?}=-=BsO97^z4O@hfMTz4PC'
        'Lopc}eac4v32a0IY{bAu6l_ETY(&9E5^PL>jU?EZ1{+bZkqodg2{xi&V+L#_!A2Bp%z=$vU?T}OVqjwtY%G9{G}uUijU?C@53un('
        '*jNG^`@qHm*q8+yGhkyHY$U-(9Bf3v#!0ZT3^tB|jiX@W2-pz7#zC-g0BkIQjYY7r7i=tmjXAK91{*VABLz05z(x{mB*4Zv*oX$$'
        '5W&VW*jNM`NwCoe8-1|R2OE8`(FYrSu+aw_ea=Rov(e{l^f?=S&PJcJ(dTURIU9Y>MxV3M=WO&j8-313pR>{DZ1g!Bea=RovC(Jg'
        'dq_h_Lr4SV!1P1IfWk0%0t}G=3{k)k0SvJK3^BkE1q^Y(5CIHRfME(SqyjL+0YeHfL;*tzFvI{u8ZaaQLj*9)0){ET5CaU0fME_W'
        'qyR%A0K<O3uop1Q0)`Y|m;ek>z;F~W2!P=LU|0kU3xFXF7*c>C2^hu!Lj*9K1`H<w!*RfH6fhhH3<m+je!#E@81?{$Il!<RFr)y('
        'Bw$DYhFAcGEMQ0jhMR!l5?~Mk!!lr41Pn>QFaQh#z%T#|0}jK0!!Y153^)t}4#R-MFyJr@I1B?0!+^su;4ln03<D0sfWt80Fbp^h'
        '0}jJrYiI~*2x<7r)4(Th_}qodW_fq0O&ki;CS+}`tz^E}lP$&2ynS~pP1yT)D6$%cyy@Bt7ugKCKTrHJ`{>a+<gS|1Ryu4l+Aq0|'
        '>KwwBI){C{P|W7Ve4$t_7sOIt6iZbx$7&lnu}~C?tkRG#6^mI+>$ABExhpqSYtxm+x1R&)+H<ccUByzjpMZ|m-eS8xI#VGy-boE}'
        '&oK84b5AZX<F_|9--fuzY?5|;Ef$Ha|0NoUnA^_K5}7ne(~f&0<J$8hnR&EW<xRqp>ra`&T>qRND7+~Q!3@C+fH|!jDvhl2mf-If'
        'QPw|Y$Ske@j&b@K^|!C2kWa~H<N^5u`J=syJ=wHfiR9O>D~2u@x_=Z_lVGI?lRdB{+$M^lpx~jHyw1_kTbq8NLy!$t@KM(^r6t@}'
        'E%Mm5epP8$896(3)2|<yf~Ff5SrNX^mlfHxR)p92VoSfReUakF)5;Zp4R0;NTZ{14g5O%K>r^?siKi>)#>ji@&$EZzNFe0K14P6@'
        'L<B^P1ww8TM5I7OJV3+@h?oHpX%G<s5pfWa0ug%xA$I{pBtgVJ5Rn2AV<2JyL`(&U*asqJKtvow2q0n+M5IAP5=2Bm#9<Jz1R~}^'
        'L<&U2LBtA(I2H)GOCVwaM9hGQB#4NDh&+fm4I-97#0wzeAc%MlL@a=a-5_ELM8pF`2p~cP5lIkn4Mb!?L>ffg0}*#X#0H2UAmS#7'
        'xWtJNIT6d8h(%6B5=78%B#`htGW0fv-kqU$Z|Hq6^gbMV9}T_xL+`=Rd&oVX4$m9TLxpgJaD;FK;NW+SUGG`>ou{N$p7?-#lRxZ|'
        'xp7-Ht!I4bJ~+*FOQ9L2YHem-RhpJ=6rM26wf;AnC;JQQ|6u9!mornf{x8~=6x%jaU600whm6O(&32fMs?(&j{sofKu|QH9RG9=+'
        'CIOX629nZvKxGmEm6?XhB%m^5P?<DTCIyvALS@DSN$DP_%p6o^cR*z(p)v`mOe~->2ca?tpfXEPnMJ6~UZ~6hRAvq;lZML7KxI-;'
        'nJK7D5-O8`%8Wy0qJgCJ3{)lql{pQSS%J!&g36qP%A5$O%yFp9F{sRoP?@7pnHQikN1!r?p)vwgW)Uirgv!*RGIgj-9V%0Y%G9AU'
        'b*M}oDpQBb)S)tUt}=D5GIg#pb*?gXo|M*kQd;LpX`Lsfb)J;gc~V;ENok!YrFEW^)_GD|=SgXuC#7|sl-5VWlJ=hGu660JsWf%1'
        '^~luJyK#EUI~#w>)KroSgKMWD4gb;9)PeYxsi_ds5YiA*AJRmdhH}|^>*B~|&lNawf~p1Pi84FAQFHw9s#UKo8?`X3hl&v@#{ZXM'
        '%=&NF?G)FQ1dZ!|e_C8m2Nl9y{~6uq3q<rtB8=!EpCO-*@i_ssSV+I{vhR;#y4+yzuy}6)vByDnDhMqr8<wGJ^k)CW=#`)KKe3#B'
        'lKuHDqx{eDrxmR1$>H>XYtMKS1l!fFUb>=tMJw75SuoT!wdMDPCLo0ig4vauiqKM4RaTzbCMo&Ss!Qv4!`p;VR6<eNA}Z_c1PV-H'
        '!8I(nh6UH~@q>_tkcPmM&2h^w{cL@*DZ)~z+4avSXree4e}*TUX1sqcwOxAn@kP}zt<(OS+{4lno^A4SMlT!mCa=7Qo_fYAOBuaY'
        '-L|YLmj5cZ_d2$pNSbt2Q>RU;8f(SeG%ckgSca^btGdzgAEH_{^p4k}|8F{w8{;i+?;Y%|FN%97fjxL-c9o{Os*aM?Et?9<qs;Zh'
        'mzlbL92=#sTg%<#ldCj}-{(>MN+e2G(La3EaG&4`c5O5N2LGQv@McT^00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
