# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/thomas/git/CyphalDemo/public_regulated_data_types/reg/udral/physics/thermodynamics/PressureTempVarTs.0.1.dsdl
#
# Generated at:  2022-05-06 20:25:55.244809 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.udral.physics.thermodynamics.PressureTempVarTs
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.si.unit.pressure
import uavcan.si.unit.temperature
import uavcan.time


def _restore_constant(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class PressureTempVarTs_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 timestamp:      None | uavcan.time.SynchronizedTimestamp_1_0 = None,
                 pressure:       None | uavcan.si.unit.pressure.Scalar_1_0 = None,
                 temperature:    None | uavcan.si.unit.temperature.Scalar_1_0 = None,
                 covariance_urt: None | _NDArray_[_np_.float16] | list[float] = None) -> None:
        """
        reg.udral.physics.thermodynamics.PressureTempVarTs.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param timestamp:      uavcan.time.SynchronizedTimestamp.1.0 timestamp
        :param pressure:       uavcan.si.unit.pressure.Scalar.1.0 pressure
        :param temperature:    uavcan.si.unit.temperature.Scalar.1.0 temperature
        :param covariance_urt: saturated float16[3] covariance_urt
        """
        self._timestamp:      uavcan.time.SynchronizedTimestamp_1_0
        self._pressure:       uavcan.si.unit.pressure.Scalar_1_0
        self._temperature:    uavcan.si.unit.temperature.Scalar_1_0
        self._covariance_urt: _NDArray_[_np_.float16]

        if timestamp is None:
            self.timestamp = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(timestamp, uavcan.time.SynchronizedTimestamp_1_0):
            self.timestamp = timestamp
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(timestamp).__name__}')

        if pressure is None:
            self.pressure = uavcan.si.unit.pressure.Scalar_1_0()
        elif isinstance(pressure, uavcan.si.unit.pressure.Scalar_1_0):
            self.pressure = pressure
        else:
            raise ValueError(f'pressure: expected uavcan.si.unit.pressure.Scalar_1_0 '
                             f'got {type(pressure).__name__}')

        if temperature is None:
            self.temperature = uavcan.si.unit.temperature.Scalar_1_0()
        elif isinstance(temperature, uavcan.si.unit.temperature.Scalar_1_0):
            self.temperature = temperature
        else:
            raise ValueError(f'temperature: expected uavcan.si.unit.temperature.Scalar_1_0 '
                             f'got {type(temperature).__name__}')

        if covariance_urt is None:
            self.covariance_urt = _np_.zeros(3, _np_.float16)
        else:
            if isinstance(covariance_urt, _np_.ndarray) and covariance_urt.dtype == _np_.float16 and covariance_urt.ndim == 1 and covariance_urt.size == 3:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._covariance_urt = covariance_urt
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                covariance_urt = _np_.array(covariance_urt, _np_.float16).flatten()
                if not covariance_urt.size == 3:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'covariance_urt: invalid array length: not {covariance_urt.size} == 3')
                self._covariance_urt = covariance_urt
            assert isinstance(self._covariance_urt, _np_.ndarray)
            assert self._covariance_urt.dtype == _np_.float16  # type: ignore
            assert self._covariance_urt.ndim == 1
            assert len(self._covariance_urt) == 3

    @property
    def timestamp(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 timestamp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._timestamp = x
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def pressure(self) -> uavcan.si.unit.pressure.Scalar_1_0:
        """
        uavcan.si.unit.pressure.Scalar.1.0 pressure
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._pressure

    @pressure.setter
    def pressure(self, x: uavcan.si.unit.pressure.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.pressure.Scalar_1_0):
            self._pressure = x
        else:
            raise ValueError(f'pressure: expected uavcan.si.unit.pressure.Scalar_1_0 got {type(x).__name__}')

    @property
    def temperature(self) -> uavcan.si.unit.temperature.Scalar_1_0:
        """
        uavcan.si.unit.temperature.Scalar.1.0 temperature
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._temperature

    @temperature.setter
    def temperature(self, x: uavcan.si.unit.temperature.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.temperature.Scalar_1_0):
            self._temperature = x
        else:
            raise ValueError(f'temperature: expected uavcan.si.unit.temperature.Scalar_1_0 got {type(x).__name__}')

    @property
    def covariance_urt(self) -> _NDArray_[_np_.float16]:
        """
        saturated float16[3] covariance_urt
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._covariance_urt

    @covariance_urt.setter
    def covariance_urt(self, x: _NDArray_[_np_.float16] | list[float]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.float16 and x.ndim == 1 and x.size == 3:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._covariance_urt = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.float16).flatten()
            if not x.size == 3:  # Length cannot be checked before casting and flattening
                raise ValueError(f'covariance_urt: invalid array length: not {x.size} == 3')
            self._covariance_urt = x
        assert isinstance(self._covariance_urt, _np_.ndarray)
        assert self._covariance_urt.dtype == _np_.float16  # type: ignore
        assert self._covariance_urt.ndim == 1
        assert len(self._covariance_urt) == 3

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.timestamp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.pressure._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.temperature._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        assert len(self.covariance_urt) == 3, 'self.covariance_urt: saturated float16[3]'
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.covariance_urt)
        _ser_.pad_to_alignment(8)
        assert 168 <= (_ser_.current_bit_length - _base_offset_) <= 168, \
            'Bad serialization of reg.udral.physics.thermodynamics.PressureTempVarTs.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> PressureTempVarTs_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "timestamp"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "pressure"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.si.unit.pressure.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "temperature"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.si.unit.temperature.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f3_ holds the value of "covariance_urt"
        _f3_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.float16, 3)
        assert len(_f3_) == 3, 'saturated float16[3]'
        self = PressureTempVarTs_0_1(
            timestamp=_f0_,
            pressure=_f1_,
            temperature=_f2_,
            covariance_urt=_f3_)
        _des_.pad_to_alignment(8)
        assert 168 <= (_des_.consumed_bit_length - _base_offset_) <= 168, \
            'Bad deserialization of reg.udral.physics.thermodynamics.PressureTempVarTs.0.1'
        assert isinstance(self, PressureTempVarTs_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'timestamp=%s' % self.timestamp,
            'pressure=%s' % self.pressure,
            'temperature=%s' % self.temperature,
            'covariance_urt=%s' % _np_.array2string(self.covariance_urt, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
        ])
        return f'reg.udral.physics.thermodynamics.PressureTempVarTs.0.1({_o_0_})'

    _EXTENT_BYTES_ = 21

    _MODEL_: _pydsdl_.StructureType = _restore_constant(
        'ABzY8Q-pP50{^vG>u(%a72mbvcj7#pSCcfoDJ5Q)?9^U+olT)Ya0qFqaiYWx0g()MX0G>Mdv<1+d&l-xszg748fhd(${_V00Oe2U'
        'pHK-9@U2Kld_bTGiLcOaaL&w~-Ss1Y5JZZ9XYS*ibI<FZyFWbi(_fyb<o}Xa!mcY_&#)wm1og!G)b^NRIYB23q);qNj@(yK?5H?m'
        'Yu%7#PqVoXvk$UbGGh6(1M`iDwT;+~sAq({D}^Hs#aYw|+%7D@&$|(m68E!C_<%-hGE2s-Efz@;_!+MxV-Ga_G&3t^^~c$VSu$l&'
        'r6OU+iplH|h<kyey;WH<a#JwR?JGEGxl~b0q1Jq;7~~_#rI>Cx)HjsqFynsLcX$-|;(g|>!GKh>6J~sjPncD+f|~HdAe|r6+h<;+'
        'M;M8YP+|-8n0e2aqU|&HZC|lAi*}oB%Cd#BJm$9*&&(ER=}@UGFc)ZfAvt}wWQ5y{6_~q?Q(&6vkFtANa?%1FeV0b=AfqR-4M&>-'
        'b4P(>PT;#)a>#N6Cwuspp-N?qGvdb`n?)p8Cj+Y_QJgBm=@ug)m6Ewc3g2Nw1|3Fd1R^3Dbx8+4eMN*1>+_Y$m_(*}9GC`?Xv1_('
        '7|ghmuR;S8n@ToEgd{Fo7hn?-vZzkO&=U?-;B$i@8z+t;<kQ=Nl48jw!BNC!Bw{~^!8fpdJqkK~?y~2;oEhnWVl28sBxCs^Cjh=O'
        'go6sd4WrSPfV1VQh+O(4oC1{FqF&5UOBE2GZK0Xq&$<_E7y9+)o6B`D3E37d=*b)kI=(qMNl2YE9ygbFTNaj6JBSr&G+Is4Wi*mk'
        '$Tk-a$EgrJr@98YPL`K)o&$S9?-*hyBHKaixgZE65EA=7b0CvwB)o2+0t5mPO7^q`v%xmd7Cq7gsfq`&#8tU?n08}eK`2NA#%xD`'
        'y?h06Oq@taA&ufND;~sxaOx}9S4qte6uEh0jzA>%V9N;PIW&Txh(om3RbqD`Nl{`*yIw$ZAA_TyIvBa)Yo)752i0%GV#%rJp@%Wt'
        '+8(Rt%L@_ftZ%3egMlJORnHF)6tfD$0&NiCtPhSMU_@zTkO<Ss_)6eony6mh@fm(mQ<uyZf0e&xRxqFVY>_%+@2#4vcfP%v@ww#k'
        'cUctd6`jW$_zkVG=?B}sktL&6u27b|Towhk6JoK$&>AcW<M;CTq+Y2HZzdCPWCusF9NyG4%qP|P3^kK>Y_nu$pblDgx2U;ziW)!1'
        '7kNE~g5oj|3hBh$>`5|ht&1JzTIeWCxY=rQ+>${YISeK|W`z{WMKXrq2|G(B?n0g4xr?Jup*&UJfWpB8EbOBYJdjXXGTas_OD0#k'
        'A$aWu>jYVHK8$ThVGC-1?4jg-t%VJvMTrGYXtgZ4cwm_|7L0iV&6X)FY%><864b*&VChuNo`5@kv09`)N+2i!;|3~05J6o)b7KTU'
        'dQ(VUwH-v8^*lG^fXv)`xlo81#dqZzFbKT3s0Mj4=*xi*F4`Qj4eT3qpwziqFh;H&04JzZWj)TbaSPT2QC)`25$j?g;^C^;WCm7c'
        '+XE9_E+eL2#Np6t?{}6Q{)SNR=HK^OFPxKMD+sfMyoibHcI*KB16I8a{?g^~4&)_OLDavDMlFX!A;|cn<mg@MVwK#th}$^38hajG'
        '1bb(B^Cwx&Y^BnMD?KbYWafBm!#O*`#|sV!x`V_RUUCpE$keRjzDjBiX&gozO3g$1djzqXnxlGrOplLioY3Qwh@+`FrPm)u98b+7'
        'h=)>hTCYEfIF*{m^!#zek<>h)`OF}mNX?Uo$5QhY;&f`BMm(IFXAmb-^Q_+gl9qc;%Q>(4T+s4fMm(RI7ZJ~;<|~LVr6xf<o0^vp'
        '&!pz7h^JHY3y7yu^EJeisrg03nbf?j^_oRIo|-kS-yGu6)O=m*`6a|7sd+`~Ti53`wBBzZPNe3%)_(zUEHxYY9E;i>OZq&yUx!n3'
        'S)c2wwr@+H?^@w^^G%Ik*7y~TZ)yCh#;<Aoy2e`?A8O<pcQk&a@nen8G=8G-Q;nZ#e6I2H0&kC3HF35iY9-MsiCZP{uq1d%?3Bbu'
        'CGl}dJS&M$O5)R!_^c$Jm&E6qh@sDey8&(#Eb@BH#u5*A&xGoCo^weBudrUfIncOX)QzhYMhxwX5$d+uxbINN&3#?#0Fw*J#7(%F'
        ')vi_)E<yqqVS~?p1lo0I8<@t}g}#-{E-uYCT8+h}<>kdzv(aibueBByuFfwlv=*0IOU;GlYmMg8QgKn`XBdT^5Y&JJ@ZZEX<=3G$'
        '{E`1o@|7q2#w!0Nzg6RJ^LMz(-{rUYD!-EqNdeUmPXhN}d6q0WTAXJ0<-pgTAY=Z3f2Sxr-{V%VI=MZH57Z<AHHmvzig*Xk>BIlv'
        'gRHC{lK*P8XaBzRLi+=)e`$~P6+C9J7XD`r`29YU^FRD|cHU&(78KS2J8z6uD;55a7n_>@iT^p78c;an&;S2c-7RpBVWELI_&FCv'
        'v<r`%o7lq?*WPs;+Wm$)Vlj{5!$Uvr`qn)*Xx)+JW^;Z?+b)@ahgL`(p}LtleDIkcB`5B&kSTHSZ8>CZ;?~_3IhN+<?U?gmjrrUf'
        ')dQ?C?F3uUxKnsrS#hK=(SL?7i#Wsw5xku^w3#>$%`mpo#p|Wq0uLLQ+#$8~z=Jj)yB%DhN8wbPI26Sm>p!%hGr6z3ko@+a!)AP*'
        ')a#^3)yEC^Ug&?nUPKlQHgK@`dfWihF^sYr|203(|Hgm2aT>$z?;DE%8)x88{DQzshM_xzXL<hH0JfaPuLD^!z5DlpEIGID7XnEB'
        'g+1w?{JhsWViV@Y0v;NAU*38R#2cweSmxntR(FB$4Dz~jMfcaYt1)@U##WP+eZDB3ZP3#dzj?sJNXB;F41!boC7@uxw*==!EBkl('
        'G#GEE;Gu$@yMJJVhB1r%8MMUs8_2)rw(%|SMgFnz4p9HA_22KMdkX@*g#n(&HUBG<IQkGqANEJf#k+?$j(~(>{SHj*46d)n`-eAX'
        'd+VRU#IybUcMoHd8UF-{X`YJL5&!@'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
