# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/thomas/git/CyphalDemo/public_regulated_data_types/uavcan/metatransport/ethernet/Frame.0.1.dsdl
#
# Generated at:  2022-05-06 20:25:54.676190 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.metatransport.ethernet.Frame
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.metatransport.ethernet


def _restore_constant(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Frame_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 destination: None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray  = None,
                 source:      None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray  = None,
                 ethertype:   None | uavcan.metatransport.ethernet.EtherType_0_1 = None,
                 payload:     None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str = None) -> None:
        """
        uavcan.metatransport.ethernet.Frame.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param destination: saturated uint8[6] destination
        :param source:      saturated uint8[6] source
        :param ethertype:   uavcan.metatransport.ethernet.EtherType.0.1 ethertype
        :param payload:     saturated uint8[<=9216] payload
        """
        self._destination: _NDArray_[_np_.uint8]
        self._source:      _NDArray_[_np_.uint8]
        self._ethertype:   uavcan.metatransport.ethernet.EtherType_0_1
        self._payload:     _NDArray_[_np_.uint8]

        if destination is None:
            self.destination = _np_.zeros(6, _np_.uint8)
        else:
            if isinstance(destination, (bytes, bytearray)) and len(destination) == 6:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._destination = _np_.frombuffer(destination, _np_.uint8)  # type: ignore
            elif isinstance(destination, _np_.ndarray) and destination.dtype == _np_.uint8 and destination.ndim == 1 and destination.size == 6:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._destination = destination
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                destination = _np_.array(destination, _np_.uint8).flatten()
                if not destination.size == 6:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'destination: invalid array length: not {destination.size} == 6')
                self._destination = destination
            assert isinstance(self._destination, _np_.ndarray)
            assert self._destination.dtype == _np_.uint8  # type: ignore
            assert self._destination.ndim == 1
            assert len(self._destination) == 6

        if source is None:
            self.source = _np_.zeros(6, _np_.uint8)
        else:
            if isinstance(source, (bytes, bytearray)) and len(source) == 6:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._source = _np_.frombuffer(source, _np_.uint8)  # type: ignore
            elif isinstance(source, _np_.ndarray) and source.dtype == _np_.uint8 and source.ndim == 1 and source.size == 6:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._source = source
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                source = _np_.array(source, _np_.uint8).flatten()
                if not source.size == 6:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'source: invalid array length: not {source.size} == 6')
                self._source = source
            assert isinstance(self._source, _np_.ndarray)
            assert self._source.dtype == _np_.uint8  # type: ignore
            assert self._source.ndim == 1
            assert len(self._source) == 6

        if ethertype is None:
            self.ethertype = uavcan.metatransport.ethernet.EtherType_0_1()
        elif isinstance(ethertype, uavcan.metatransport.ethernet.EtherType_0_1):
            self.ethertype = ethertype
        else:
            raise ValueError(f'ethertype: expected uavcan.metatransport.ethernet.EtherType_0_1 '
                             f'got {type(ethertype).__name__}')

        if payload is None:
            self.payload = _np_.array([], _np_.uint8)
        else:
            payload = payload.encode() if isinstance(payload, str) else payload  # Implicit string encoding
            if isinstance(payload, (bytes, bytearray)) and len(payload) <= 9216:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._payload = _np_.frombuffer(payload, _np_.uint8)  # type: ignore
            elif isinstance(payload, _np_.ndarray) and payload.dtype == _np_.uint8 and payload.ndim == 1 and payload.size <= 9216:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._payload = payload
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                payload = _np_.array(payload, _np_.uint8).flatten()
                if not payload.size <= 9216:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'payload: invalid array length: not {payload.size} <= 9216')
                self._payload = payload
            assert isinstance(self._payload, _np_.ndarray)
            assert self._payload.dtype == _np_.uint8  # type: ignore
            assert self._payload.ndim == 1
            assert len(self._payload) <= 9216

    @property
    def destination(self) -> _NDArray_[_np_.uint8]:
        """
        saturated uint8[6] destination
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._destination

    @destination.setter
    def destination(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray ) -> None:
        if isinstance(x, (bytes, bytearray)) and len(x) == 6:
            # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
            # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
            self._destination = _np_.frombuffer(x, _np_.uint8)  # type: ignore
        elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size == 6:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._destination = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.uint8).flatten()
            if not x.size == 6:  # Length cannot be checked before casting and flattening
                raise ValueError(f'destination: invalid array length: not {x.size} == 6')
            self._destination = x
        assert isinstance(self._destination, _np_.ndarray)
        assert self._destination.dtype == _np_.uint8  # type: ignore
        assert self._destination.ndim == 1
        assert len(self._destination) == 6

    @property
    def source(self) -> _NDArray_[_np_.uint8]:
        """
        saturated uint8[6] source
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._source

    @source.setter
    def source(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray ) -> None:
        if isinstance(x, (bytes, bytearray)) and len(x) == 6:
            # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
            # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
            self._source = _np_.frombuffer(x, _np_.uint8)  # type: ignore
        elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size == 6:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._source = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.uint8).flatten()
            if not x.size == 6:  # Length cannot be checked before casting and flattening
                raise ValueError(f'source: invalid array length: not {x.size} == 6')
            self._source = x
        assert isinstance(self._source, _np_.ndarray)
        assert self._source.dtype == _np_.uint8  # type: ignore
        assert self._source.ndim == 1
        assert len(self._source) == 6

    @property
    def ethertype(self) -> uavcan.metatransport.ethernet.EtherType_0_1:
        """
        uavcan.metatransport.ethernet.EtherType.0.1 ethertype
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._ethertype

    @ethertype.setter
    def ethertype(self, x: uavcan.metatransport.ethernet.EtherType_0_1) -> None:
        if isinstance(x, uavcan.metatransport.ethernet.EtherType_0_1):
            self._ethertype = x
        else:
            raise ValueError(f'ethertype: expected uavcan.metatransport.ethernet.EtherType_0_1 got {type(x).__name__}')

    @property
    def payload(self) -> _NDArray_[_np_.uint8]:
        """
        saturated uint8[<=9216] payload
        DSDL does not support strings natively yet. To interpret this array as a string,
        use tobytes() to convert the NumPy array to bytes, and then decode() to convert bytes to string:
        .payload.tobytes().decode()
        When assigning a string to this property, no manual conversion is necessary (it will happen automatically).
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._payload

    @payload.setter
    def payload(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str) -> None:
        x = x.encode() if isinstance(x, str) else x  # Implicit string encoding
        if isinstance(x, (bytes, bytearray)) and len(x) <= 9216:
            # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
            # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
            self._payload = _np_.frombuffer(x, _np_.uint8)  # type: ignore
        elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size <= 9216:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._payload = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.uint8).flatten()
            if not x.size <= 9216:  # Length cannot be checked before casting and flattening
                raise ValueError(f'payload: invalid array length: not {x.size} <= 9216')
            self._payload = x
        assert isinstance(self._payload, _np_.ndarray)
        assert self._payload.dtype == _np_.uint8  # type: ignore
        assert self._payload.ndim == 1
        assert len(self._payload) <= 9216

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        assert len(self.destination) == 6, 'self.destination: saturated uint8[6]'
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.destination)
        assert len(self.source) == 6, 'self.source: saturated uint8[6]'
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.source)
        _ser_.pad_to_alignment(8)
        self.ethertype._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
        assert len(self.payload) <= 9216, 'self.payload: saturated uint8[<=9216]'
        _ser_.add_aligned_u16(len(self.payload))
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.payload)
        _ser_.pad_to_alignment(8)
        assert 128 <= (_ser_.current_bit_length - _base_offset_) <= 73856, \
            'Bad serialization of uavcan.metatransport.ethernet.Frame.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> Frame_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "destination"
        _f0_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, 6)
        assert len(_f0_) == 6, 'saturated uint8[6]'
        # Temporary _f1_ holds the value of "source"
        _f1_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, 6)
        assert len(_f1_) == 6, 'saturated uint8[6]'
        # Temporary _f2_ holds the value of "ethertype"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.metatransport.ethernet.EtherType_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f3_ holds the value of "payload"
        # Length field byte-aligned: True; all elements byte-aligned: True.
        _len0_ = _des_.fetch_aligned_u16()
        assert _len0_ >= 0
        if _len0_ > 9216:
            raise _des_.FormatError(f'Variable array length prefix {_len0_} > 9216')
        _f3_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, _len0_)
        assert len(_f3_) <= 9216, 'saturated uint8[<=9216]'
        self = Frame_0_1(
            destination=_f0_,
            source=_f1_,
            ethertype=_f2_,
            payload=_f3_)
        _des_.pad_to_alignment(8)
        assert 128 <= (_des_.consumed_bit_length - _base_offset_) <= 73856, \
            'Bad deserialization of uavcan.metatransport.ethernet.Frame.0.1'
        assert isinstance(self, Frame_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'destination=%s' % _np_.array2string(self.destination, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
            'source=%s' % _np_.array2string(self.source, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
            'ethertype=%s' % self.ethertype,
            'payload=%s' % repr(bytes(self.payload))[1:],
        ])
        return f'uavcan.metatransport.ethernet.Frame.0.1({_o_0_})'

    _EXTENT_BYTES_ = 9232

    _MODEL_: _pydsdl_.StructureType = _restore_constant(
        'ABzY8QiOG40{^{MTW=dh6n5HNoTM#jQ(AFTM^M@n!8U0URFEo~wodE1F(C<+5TNPUJNB7oy}O#7H8BX$A{7y7q!u#eetF;l2??nZ'
        '`~xH;{sg~;GrQ|JPU0Y5h!lA|bLPyseBXC`r~hGdG?)D86Jg7ZT+g8qmx6iXeOB?fL#sg}3?iYp(Fd26jH@b^e5Dm~vtiEMH6NM@'
        'JwScd!1L!~)~qt$X>i4qWPTI|QaM}!mp)g{yiBa}w8>>80^dMR58cex8>W;i^?hRQ8a+yxQc_f6#Ut}B`tK3hrj^kH^MZSBC!!JR'
        'GR3H}Vd|%PT$hryj6OOq*0_6v`*j6#cB?zLgOq!`!F`oE>k&&RMMEgjM2qn^{Ycb(?iPK;>s)sG8>JPYsFyrvN_mX5$|6M@fy)g%'
        'sgEtT9ocKnWjtH3N47lo%o2u6BgK4|Nq4KGPveRnMo%HD3e_^DLETR)US#yCcDNm5j9hL1ZuEgmLZwAm#;;kpdOr<9qe(9(QL9l2'
        'JW<7@7kDGUVkqq8>mip+1+tU$AgzMH{(z&8Eb)*lvAf+qx{9&GG}=8@jy;db)^;QG)ns1G&3!Xb%0GxIn0Y^K2;Y<@?Sie@#gHv%'
        '>@n-L)Mrg|4@&v;Gsc?pwGiQHaaWEj)&~seQI|(b_(=)|UAY0~l{0uYmWBu8a4cIr0Z(VE6Qw*5I0?^V3*Zz6e;Qs$j^HJj%xtD%'
        'Hd~!fvU@c(xX?)fUMo$)Mf{)JEnp~gq8yBZSXL1$SK(S$X#29&fIhu94GVUWfD(paxXn5^fK1!su9M$bC%*wbkQP6C{gBRI4txv9'
        'O~~wZx41}e&Lnr?f_|nAD(r>ik!?m7jq*!LCz#jvjCY1>l2z?4B0E2yt?^v<pPQUHZ!AHQGTr{SQ1;I)EoOm$%)G;U*3In9e{hpz'
        '^ztr_2Bv3b&&_Un;(C0GrqN0(6-?_9z=Z%-;Uo9}*5O`^0^xEjNR=t>nst4M)~r5J+e0c`Q`U!R3IROuI1L%nUk}+2PgIN^UPQ58'
        'TeQ0y$f&-vSR4qf?hY#aWLUZVb%BH*x!ekYc~_9PRwCmH@|a3qN7mrW9sR@$gDIeJ0CYhLd(Z}z(ML96<xDzLj%}?`R<On?un5DH'
        'Rzp!Vn*!0h4p;TB%bAdo&8wuEp(!FPA}+59lu=S?kz%1xAWOV1B7EI8oy^6UjzqB|=!6vK%5%=h3W$h!XhZNb@I5>uQG<CNiI6{B'
        'k)XEa1qDnI3@h0ZE|>U}3P^<$iIU$$8&V4-Nz3Gz-HDAtwa8po`1KuXwvFgxNOYWiVQP)ipRj%mSwCi3-zIysmF&YweUrhngYQT6'
        '@tX`s5RRW-!>gxEE#yw>BW)$G+0mI!w{19ow$x`4oL=gY{^KYB7OVcQ(r<^7Reo%~o#Z<T(&g&-67%bPulX=YR}+QD_<PA{4lZ8L'
        'k-pp>O3I_G^4G`qHq5$!<Z5{V!|`=hPc6rx#eQT_(?m!o5=CyuI0#A2{=kXIL>yWmy+TUj(isN_2#5PN$9XsmZ$lA&gLmL>_&tWt'
        '*5UIqY`_;2@Fjc&U&A->Eqn*x!w>MIK9u}i>LwHXWQp@}!iMvc=bY)3I!M6uZNjk^VPq+6<#eRz6UAjCvcN}m2=VZ&s)lad2wz0}'
        'Tj)#F-Z1bjCeg%SB^C&lKR1fy(#l(l1zK3SR#++*R?c3zu|f;wsmX;)z1Z-}=Bl&zXKMDBZU6seIR%eOece+vX(+sr_Wl;`-s<c='
        '%E-8F`{&d+#NBYKaq4;7_8+P79Yocg3{~CEcbr&sIsX7=vJozU3jhE'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
