# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2022-05-18 08:58:47.538546 UTC
# Namespace:     reg.udral.physics.kinematics

# There are no data types in this namespace. There may be data types in nested namespaces.
