# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2022-05-18 08:59:57.553712 UTC
# Namespace:     uavcan.si.sample.energy

from uavcan.si.sample.energy.Scalar_1_0 import Scalar_1_0 as Scalar_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Scalar_1 = Scalar_1_0
