# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2022-05-18 08:39:37.866871 UTC
# Namespace:     jeroboam_datatypes

# There are no data types in this namespace. There may be data types in nested namespaces.
