# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/thomas/git/CyphalDemo/jeroboam/sensors/resistance.0.1.uavcan
#
# Generated at:  2022-05-06 20:25:55.523244 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     jeroboam.sensors.resistance
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive.scalar


def _restore_constant(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class resistance_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 value: None | uavcan.primitive.scalar.Real32_1_0 = None) -> None:
        """
        jeroboam.sensors.resistance.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param value: uavcan.primitive.scalar.Real32.1.0 value
        """
        self._value: uavcan.primitive.scalar.Real32_1_0

        if value is None:
            self.value = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(value, uavcan.primitive.scalar.Real32_1_0):
            self.value = value
        else:
            raise ValueError(f'value: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(value).__name__}')

    @property
    def value(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._value = x
        else:
            raise ValueError(f'value: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.value._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 32 <= (_ser_.current_bit_length - _base_offset_) <= 32, \
            'Bad serialization of jeroboam.sensors.resistance.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> resistance_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "value"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = resistance_0_1(
            value=_f0_)
        _des_.pad_to_alignment(8)
        assert 32 <= (_des_.consumed_bit_length - _base_offset_) <= 32, \
            'Bad deserialization of jeroboam.sensors.resistance.0.1'
        assert isinstance(self, resistance_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'value=%s' % self.value,
        ])
        return f'jeroboam.sensors.resistance.0.1({_o_0_})'

    _EXTENT_BYTES_ = 4

    _MODEL_: _pydsdl_.StructureType = _restore_constant(
        'ABzY8Q-pP50{?YXTTc`*6kfyy1QZGCgBsl@#i+yHS-d@XL6gx1!T4fG?aY)tHJwY^&SuxdL?1M6(nJ&L|MhftVG+Y5lR2H!e*MmO'
        'zV_?cKMTde@G&>DexxGd5yd2@f`6ugU>*t6I7=1R%$oDNTIQk7C41M;m_4v}zS%E!)f7oWW6WRs#AF(zH1-rrR4SDxnc_;*B*g3-'
        '=`yK!nph~9+4tl4!1@J$>WBSi%>toXOCIE!DZ6J+BXl&$n&KvBBAO7HClS?@XvYrDjDAAV+{kG+q=}bF9&^pR%u^v1RC+s%idxme'
        'ES&SF{DNZvi+dI>j+d^S#^DIbnsb{XrTSk%7D&J~5iIFwuzm@7g;Z%0rxEhHZmw(}E_chkXPA5AQcjEScE_4a#EBMB865}ui8wLs'
        'BwXi_+jw8nP@{$lwcQ-Yh+%Hm>g8&yTB|pkwN|6rYBe@mmCAa#UTM|pt$L%<+^9C{^|Ez)<pBy*>{5{<<XIA>p*77HJwy}zl4Kcn'
        'kR{qxUE+ym9c<f!(uez%=KA`2wbHy-x_cPzAr>_&$C^lj{>T|$EUdv*g}OuzF{GMBc3>`$ecodc$x^8ak8Im46P4yNWS9_)WE875'
        'v+g5!fE90}5qsP2?*XbjwT6r#b<Ug7_@yYsbcbte=AZR5pyD};Q*>pP2ZD!0vQ94C&J&a1f|-#w5d2tAXGZ?8W@+RQui}+G=L4%<'
        'dsYZgh3q6M<BZYe=<flPO~FYR2!y?L=$lFZaHc*vwr24u*RO};T^x=bWTr`)SyMU<MD^n!#hQ@H8>|ss>3YAFF-dhQCqA4ZA#gk('
        'uw|CEX%z9K^WP+R=d$fwV8Q*9Swt9F<Ck6aOTSfsr#Kq{S${4Mu-up@&f*x*o(pE3%~5E#dY-UeMw8(|Z|8vuj=K%Y@Dd#ZRdfe~'
        'Wd-#CG}_RFja7I658)9!h9_q3@J>M^jBgcdE>G?iY)r))_s}&5HU|zEUV%TX0NU{OsL=OE(GC#DA3pjep!fzjGa6I${sLh>Xj&Ep'
        '000'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
