# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/thomas/git/CyphalDemo/public_regulated_data_types/uavcan/metatransport/can/ArbitrationID.0.1.dsdl
#
# Generated at:  2022-05-06 20:25:54.681083 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.metatransport.can.ArbitrationID
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.metatransport.can


def _restore_constant(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class ArbitrationID_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self, *,
                 base:     None | uavcan.metatransport.can.BaseArbitrationID_0_1 = None,
                 extended: None | uavcan.metatransport.can.ExtendedArbitrationID_0_1 = None) -> None:
        """
        uavcan.metatransport.can.ArbitrationID.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        If no parameters are provided, the first field will be default-initialized and selected.
        If one parameter is provided, it will be used to initialize and select the field under the same name.
        If more than one parameter is provided, a ValueError will be raised.
        :param base:     uavcan.metatransport.can.BaseArbitrationID.0.1 base
        :param extended: uavcan.metatransport.can.ExtendedArbitrationID.0.1 extended
        """
        self._base:     None | uavcan.metatransport.can.BaseArbitrationID_0_1 = None
        self._extended: None | uavcan.metatransport.can.ExtendedArbitrationID_0_1 = None
        _init_cnt_: int = 0

        if base is not None:
            _init_cnt_ += 1
            self.base = base  # type: ignore

        if extended is not None:
            _init_cnt_ += 1
            self.extended = extended  # type: ignore

        if _init_cnt_ == 0:
            self.base = uavcan.metatransport.can.BaseArbitrationID_0_1()  # Default initialization
        elif _init_cnt_ == 1:
            pass  # A value is already assigned, nothing to do
        else:
            raise ValueError(f'Union cannot hold values of more than one field')

    @property
    def base(self) -> None | uavcan.metatransport.can.BaseArbitrationID_0_1:
        """
        uavcan.metatransport.can.BaseArbitrationID.0.1 base
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._base

    @base.setter
    def base(self, x: uavcan.metatransport.can.BaseArbitrationID_0_1) -> None:
        if isinstance(x, uavcan.metatransport.can.BaseArbitrationID_0_1):
            self._base = x
        else:
            raise ValueError(f'base: expected uavcan.metatransport.can.BaseArbitrationID_0_1 got {type(x).__name__}')
        self._extended = None

    @property
    def extended(self) -> None | uavcan.metatransport.can.ExtendedArbitrationID_0_1:
        """
        uavcan.metatransport.can.ExtendedArbitrationID.0.1 extended
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._extended

    @extended.setter
    def extended(self, x: uavcan.metatransport.can.ExtendedArbitrationID_0_1) -> None:
        if isinstance(x, uavcan.metatransport.can.ExtendedArbitrationID_0_1):
            self._extended = x
        else:
            raise ValueError(f'extended: expected uavcan.metatransport.can.ExtendedArbitrationID_0_1 got {type(x).__name__}')
        self._base = None

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        if self.base is not None:  # Union tag 0
            _ser_.add_aligned_u8(0)
            _ser_.pad_to_alignment(8)
            self.base._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.extended is not None:  # Union tag 1
            _ser_.add_aligned_u8(1)
            _ser_.pad_to_alignment(8)
            self.extended._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        else:
            raise RuntimeError('Malformed union uavcan.metatransport.can.ArbitrationID.0.1')
        _ser_.pad_to_alignment(8)
        assert 40 <= (_ser_.current_bit_length - _base_offset_) <= 40, \
            'Bad serialization of uavcan.metatransport.can.ArbitrationID.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> ArbitrationID_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        _tag0_ = _des_.fetch_aligned_u8()
        if _tag0_ == 0:
            _des_.pad_to_alignment(8)
            _uni0_ = uavcan.metatransport.can.BaseArbitrationID_0_1._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = ArbitrationID_0_1(base=_uni0_)
        elif _tag0_ == 1:
            _des_.pad_to_alignment(8)
            _uni1_ = uavcan.metatransport.can.ExtendedArbitrationID_0_1._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = ArbitrationID_0_1(extended=_uni1_)
        else:
            raise _des_.FormatError(f'uavcan.metatransport.can.ArbitrationID.0.1: Union tag value {_tag0_} is invalid')
        _des_.pad_to_alignment(8)
        assert 40 <= (_des_.consumed_bit_length - _base_offset_) <= 40, \
            'Bad deserialization of uavcan.metatransport.can.ArbitrationID.0.1'
        assert isinstance(self, ArbitrationID_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = '(MALFORMED UNION)'
        if self.base is not None:
            _o_0_ = 'base=%s' % self.base
        if self.extended is not None:
            _o_0_ = 'extended=%s' % self.extended
        return f'uavcan.metatransport.can.ArbitrationID.0.1({_o_0_})'

    _EXTENT_BYTES_ = 5

    _MODEL_: _pydsdl_.UnionType = _restore_constant(
        'ABzY8QiOG40{`uq*=`g^6ozND$2(w5h~dCVAY|AE3<&`eRs(_z7z+o4B1N5^>9(t_+0u(;M?wl0i9l*8PUuJ|7r91x0v>@&?!qJR'
        '2wdj0=P%D<JBe~VNanApUZ%RbzOPT)KV*KJm`tqw3->oxEYGSG49|8Qv*LVjmMV6^DA%ivy65<I6b{_4IrZ9CD-An(79D;ZJ&N*S'
        ')~K0P*>)%}m&#_XP_=#2cg>pDsJnh4?z!TY9O?1p&|BA{FlQ{;t|uQNl?eMEp#3Z=CW^_QqQ_A<WSGA1I;Ft3z33bHiY*4VzE>1x'
        'Z#Z_vY7J`8uuR`H{CK4DEhBTj8<hRPwL8YHvf+^}M}5`w?9P#^el?&6sfJ}>Y8%cozSR&Lu2Xe<XGw-Qe!u293pLxiRrBoy+wGji'
        'Aw#~&sMxgyUq!_sxq!0i`9`&F$p!2Scg^Y(#fKH9W!s&2lgwK3$LL-Z?le5#tXZaOwV&u|P?BrRE}4};MvyVAdN~Rck@Sv+!?UJk'
        'Ikkn(nUhPI-276O>W(Eh?}0@7(A9zBgeTvkj;W*SSWvRV@wVG%lvbL{Lv}o(_Ih%imfdjevgzAa^fVkb=AC8RGU8b`<oq+?cEhU&'
        'ZrPR%729Z-aus2J92KV|3vgCe;___V`%Gpnc|xvA)#K&Y=S!Mi6s8v(KMDt@R~pK!T(hh7DBRNsN)@MUxb{L&iNCqEI^=-9<`Rg)'
        'k&Z<mXIkr>+^`S|Cks=Bc#0xFp89b^nVyW)wQGJnXG>1mj-INc;f|@P<8l}~mTYn69osF$H=$IKFFm9uxplYXSik#o6b@f?{M&1v'
        '=j0<MJxm+*MilZ^C-GLQrMg_P4DOE1fZW1(<aZmkTteM#t-3y=tQ@)fYAzhZa@eqwdZ_NNx8}l$>3S``d$mnZ84fhhD02~$+jivF'
        'ZRZ%92`UxSUD<GSpV3^ZKS%lE(5hDwS2UW#l64-GWb&#`EyhC{=5pNVj}eiZ8lStEjE_sK7E^I1SBvR5Q>(>HoaxnK7X5v3W><^-'
        'ab{MFIcy)m{)5<W2<IDaj;A<+97T>Hw;{J9cOb`+JCPH}UC8&4yOHlBCy{%Qdy$0Phun{3<Oj$Pkq3|mksl!sAwNduk%y5-kVlcn'
        'kjIe)<O$?S<P`E0@-*@j<fq6p$j^{xk>`--k)I>KKwdyzL|#H(M&3j|L@MMm@(J=e@&)oG@)hz8@-6aRGw<Y*XzbRFyl$M;jhnjh'
        'P&brrEbGP--FU7WFLdLjZoJZsH@fjwH{PKU$Wy{zZiuhq2PpbVYO(3%YTPj)5ZR*VMv>Kb^5bs6B+-RQ0+^(LNvaEz1Te`0lN2x+'
        '1SUCP(g#d3z$67s62N2(n2Z9G5nwXhg~=c=82~0ZVA2mv`hZCmm}G!S8knSjNfMYOfC&Q=1||$l7??0HVPL|*gn<bI69y&>Oc<Cj'
        'FkxWAz=VMb0}}=&3``i9Ffd_Y!oY-q2?G-bCJam%m@qJ5V8XzJfe8Z>1||$l7??0HVPL|*gn<bI69y&>Oju*W8WYx-u*QTnCaf`G'
        'jR|W^SYyH(6V{lp#)LH{tTADY32RJvHBhh7D5-ie7xZZ8(a@toXz)sFuLqfu6u42ddT+hasEPG=q{5c(NY|I85VUOTKffm_M(aS4'
        ')IpV3hdW+TFo?qX?x*!TM!Mr2L!EgPE&h>ABo=>{|2%c}sX8~K&Z`S~bx~bXm(>+@RZXjF>bklS?%Q;fokhI*a;;!Lb#6n!u5PQl'
        '%|YDTw3==8ecRlvyj9)X{#+(`E{lwkYce8{5p5!)?g};u8D+XE*d%0>?W$l0AftZBC<_^-A)_Q@GzuAwKt{t|73?5nGyoapAftZB'
        's1GvALPi<LC=D5<AfqH?lz@x~G9t)`AR~f|2r?qbh#(_^j0iF!$cP{#f{X|<BFKm!BZ7<wG9t)`AR~f|2r?qbh#(_^j0iF!$cP{#'
        'f{X|<BFKm!BZ7<wG9t)`AR~f|2r?qbh#(_^j0iF!$cP{#f{X|<BFKoej7ZCfw2Vm0h_sAI%ZRj$NXv+{j7ZCfw2Vm0h_sAI%ZRj$'
        'NXv+{jHtV8P4~*y-h;aLpzf8eJsNs6Y*Du6Y?O6TTTz%_{6z{vwSDogloW@*N;~-H;&9i$7KMAKugvhgYgTPGTl?~S{A=?<6pk6b'
        'xnQh)!k-&jC2p=+;y#h_{;w*s{gIf9E5`O;#Ez`}EvEZdsLcZ(EdD8%-t`1kuV(^0RrAu9U+-JjOJ{dH&xOAMEtkJDAQ}Jw'
    )
    assert isinstance(_MODEL_, _pydsdl_.UnionType)
