# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/pi/CyphalDemo/public_regulated_data_types/uavcan/metatransport/can/Manifestation.0.1.dsdl
#
# Generated at:  2022-05-18 08:39:29.389965 UTC
# Is deprecated: yes
# Fixed port ID: None
# Full name:     uavcan.metatransport.can.Manifestation
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import warnings as _warnings_
import uavcan.metatransport.can


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Manifestation_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self, *,
                 error:                       None | uavcan.metatransport.can.Error_0_1 = None,
                 data_fd:                     None | uavcan.metatransport.can.DataFD_0_1 = None,
                 data_classic:                None | uavcan.metatransport.can.DataClassic_0_1 = None,
                 remote_transmission_request: None | uavcan.metatransport.can.RTR_0_1 = None) -> None:
        """
        uavcan.metatransport.can.Manifestation.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        If no parameters are provided, the first field will be default-initialized and selected.
        If one parameter is provided, it will be used to initialize and select the field under the same name.
        If more than one parameter is provided, a ValueError will be raised.
        :param error:                       uavcan.metatransport.can.Error.0.1 error
        :param data_fd:                     uavcan.metatransport.can.DataFD.0.1 data_fd
        :param data_classic:                uavcan.metatransport.can.DataClassic.0.1 data_classic
        :param remote_transmission_request: uavcan.metatransport.can.RTR.0.1 remote_transmission_request
        """
        _warnings_.warn('Data type uavcan.metatransport.can.Manifestation.0.1 is deprecated', DeprecationWarning)

        self._error:                       None | uavcan.metatransport.can.Error_0_1 = None
        self._data_fd:                     None | uavcan.metatransport.can.DataFD_0_1 = None
        self._data_classic:                None | uavcan.metatransport.can.DataClassic_0_1 = None
        self._remote_transmission_request: None | uavcan.metatransport.can.RTR_0_1 = None
        _init_cnt_: int = 0

        if error is not None:
            _init_cnt_ += 1
            self.error = error  # type: ignore

        if data_fd is not None:
            _init_cnt_ += 1
            self.data_fd = data_fd  # type: ignore

        if data_classic is not None:
            _init_cnt_ += 1
            self.data_classic = data_classic  # type: ignore

        if remote_transmission_request is not None:
            _init_cnt_ += 1
            self.remote_transmission_request = remote_transmission_request  # type: ignore

        if _init_cnt_ == 0:
            self.error = uavcan.metatransport.can.Error_0_1()  # Default initialization
        elif _init_cnt_ == 1:
            pass  # A value is already assigned, nothing to do
        else:
            raise ValueError(f'Union cannot hold values of more than one field')

    @property
    def error(self) -> None | uavcan.metatransport.can.Error_0_1:
        """
        uavcan.metatransport.can.Error.0.1 error
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._error

    @error.setter
    def error(self, x: uavcan.metatransport.can.Error_0_1) -> None:
        if isinstance(x, uavcan.metatransport.can.Error_0_1):
            self._error = x
        else:
            raise ValueError(f'error: expected uavcan.metatransport.can.Error_0_1 got {type(x).__name__}')
        self._data_fd = None
        self._data_classic = None
        self._remote_transmission_request = None

    @property
    def data_fd(self) -> None | uavcan.metatransport.can.DataFD_0_1:
        """
        uavcan.metatransport.can.DataFD.0.1 data_fd
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._data_fd

    @data_fd.setter
    def data_fd(self, x: uavcan.metatransport.can.DataFD_0_1) -> None:
        if isinstance(x, uavcan.metatransport.can.DataFD_0_1):
            self._data_fd = x
        else:
            raise ValueError(f'data_fd: expected uavcan.metatransport.can.DataFD_0_1 got {type(x).__name__}')
        self._error = None
        self._data_classic = None
        self._remote_transmission_request = None

    @property
    def data_classic(self) -> None | uavcan.metatransport.can.DataClassic_0_1:
        """
        uavcan.metatransport.can.DataClassic.0.1 data_classic
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._data_classic

    @data_classic.setter
    def data_classic(self, x: uavcan.metatransport.can.DataClassic_0_1) -> None:
        if isinstance(x, uavcan.metatransport.can.DataClassic_0_1):
            self._data_classic = x
        else:
            raise ValueError(f'data_classic: expected uavcan.metatransport.can.DataClassic_0_1 got {type(x).__name__}')
        self._error = None
        self._data_fd = None
        self._remote_transmission_request = None

    @property
    def remote_transmission_request(self) -> None | uavcan.metatransport.can.RTR_0_1:
        """
        uavcan.metatransport.can.RTR.0.1 remote_transmission_request
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._remote_transmission_request

    @remote_transmission_request.setter
    def remote_transmission_request(self, x: uavcan.metatransport.can.RTR_0_1) -> None:
        if isinstance(x, uavcan.metatransport.can.RTR_0_1):
            self._remote_transmission_request = x
        else:
            raise ValueError(f'remote_transmission_request: expected uavcan.metatransport.can.RTR_0_1 got {type(x).__name__}')
        self._error = None
        self._data_fd = None
        self._data_classic = None

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        if self.error is not None:  # Union tag 0
            _ser_.add_aligned_u8(0)
            _ser_.pad_to_alignment(8)
            self.error._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.data_fd is not None:  # Union tag 1
            _ser_.add_aligned_u8(1)
            _ser_.pad_to_alignment(8)
            self.data_fd._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.data_classic is not None:  # Union tag 2
            _ser_.add_aligned_u8(2)
            _ser_.pad_to_alignment(8)
            self.data_classic._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.remote_transmission_request is not None:  # Union tag 3
            _ser_.add_aligned_u8(3)
            _ser_.pad_to_alignment(8)
            self.remote_transmission_request._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        else:
            raise RuntimeError('Malformed union uavcan.metatransport.can.Manifestation.0.1')
        _ser_.pad_to_alignment(8)
        assert 40 <= (_ser_.current_bit_length - _base_offset_) <= 568, \
            'Bad serialization of uavcan.metatransport.can.Manifestation.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> Manifestation_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        _tag0_ = _des_.fetch_aligned_u8()
        if _tag0_ == 0:
            _des_.pad_to_alignment(8)
            _uni0_ = uavcan.metatransport.can.Error_0_1._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Manifestation_0_1(error=_uni0_)
        elif _tag0_ == 1:
            _des_.pad_to_alignment(8)
            _uni1_ = uavcan.metatransport.can.DataFD_0_1._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Manifestation_0_1(data_fd=_uni1_)
        elif _tag0_ == 2:
            _des_.pad_to_alignment(8)
            _uni2_ = uavcan.metatransport.can.DataClassic_0_1._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Manifestation_0_1(data_classic=_uni2_)
        elif _tag0_ == 3:
            _des_.pad_to_alignment(8)
            _uni3_ = uavcan.metatransport.can.RTR_0_1._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Manifestation_0_1(remote_transmission_request=_uni3_)
        else:
            raise _des_.FormatError(f'uavcan.metatransport.can.Manifestation.0.1: Union tag value {_tag0_} is invalid')
        _des_.pad_to_alignment(8)
        assert 40 <= (_des_.consumed_bit_length - _base_offset_) <= 568, \
            'Bad deserialization of uavcan.metatransport.can.Manifestation.0.1'
        assert isinstance(self, Manifestation_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = '(MALFORMED UNION)'
        if self.error is not None:
            _o_0_ = 'error=%s' % self.error
        if self.data_fd is not None:
            _o_0_ = 'data_fd=%s' % self.data_fd
        if self.data_classic is not None:
            _o_0_ = 'data_classic=%s' % self.data_classic
        if self.remote_transmission_request is not None:
            _o_0_ = 'remote_transmission_request=%s' % self.remote_transmission_request
        return f'uavcan.metatransport.can.Manifestation.0.1({_o_0_})'

    _EXTENT_BYTES_ = 71

    _MODEL_: _pydsdl_.UnionType = _restore_constant_(
        'ABzY8!LWp40{`t@TWs9MdfwG_<?%(nJ9cO@zDV><k#DhbapJ^js$jY~hEL+^<zT&%D0BBnD|L6}N(U&A^Uy*m7O2o{0rjCk9@;`^'
        'UxK!274)Gg4hpCb1x`^E5Q?_QqtK^QpbvWN{Ny)WlFQ+)Rx8C$7$6>MhBN=iA^(s6d^4Q=wCj&P{_BMOU*+7~;$&%ZdMHyei@EG{'
        '?q}KYX>%wuF*`FiTgsKqYNhX!LT<M3@#36W{k(el=hfe-8kO!$Av+_=2IjNRCbEU08MB-%7qf-Z+-$KtL^<hfAva}~M7F40t)w!~'
        '%wmZStwg2wF^)g4@&r%*UiIhI3d>~6<zjApzHFANKM^Jrz}&N{mF^F6=JaF@)V|DQww%qB38}Dh;K$|S{6u-aX!@{Q-IcRS)W23N'
        '&K9dyuhl1kS^IxdwGLMHKg>=}<_b^!Cat5D)8R0m&E_V>RX-Mq*SfgO@mx7GZ5E!Ett!_`;{r~iTItG6&Q4UVf%)-l<*278GUJO*'
        'Puo=|&AFmEku95()z2yiGgG+*b23BNGs4(MmBX3R?0j*;6a~{}W-co%RC+0y&W(%P_)y%>g@=^;x#+CqtHP=^OE<A&E?2GWd$2fX'
        'WvAaaXJ)IFGjsFf)47RE(R?~TP4;R%TdG!iobIbu4){8-TIsZN589nLG(2=;h<c`4u0E=Yi?XsMfvIQ~%G6cQaua6tGi$K&$%A)4'
        '(#PjZx=FS4qDf7?p_{p~Wft{pLC+P+qK<f4veVOx`ct!D76}o~pDK#p(ZxYlpUjoS%^uGdCd?t~(eY`4bwJ*pTDJ@H<>24d%KrCq'
        '<=?RX{;~K|-mcEf>|C{?s~RaS&Wz8BjuO|G79A&UJ^}sF96=P%k^5x!WG1Yfcy6rsD~IqP)tzL0NTnamPfuryi@{RS!n5r3yjlH&'
        's=@W;(ztM_Ij5m2PtA{u%bm#;!~;bK*#$c2&CJYBin~W`^CZ<vEb|Veos@Pg^Dg||jlX-4_EOrl%u^`uqqKXO??XAGbl)=HPibnI'
        'AE2~nnIA;GLpZM=^$$~eXqg|O^x!f-O6h@RevH!n%ltT{Y?+@xyC*5_Tjr<G{!5hhF7wl{a|U=`hCPka&SicUcF$3oT;@9LzvA>8'
        'KacbR(u+thAss+Eh}1xO8R-?ISCL*rdL8Ky(pQlVBfWw2Cem9-ZzH{f^fjb+k&YmJ9qAiL-$eQr(tAkXM*0rY`$$KTjv=*>E+Ab('
        'x`K2S=^D~?q#H;#k#0F@I+eu1DS2SXgAsW!Di6lwfh7+X<iV0WSdj;-@?cFKtjmK9d9W!Dws0^n-Ua5uoFFE8%OG#OG(Jys+if}|'
        'KUf(c?s0g;@X!p=iHA%sS4FjcN%+=r_cd}(`5Jj&u;mBu*S$v!Pct2EGwOHfyG21bMVnJTjBc$4>WZ?p_p&9k=@wP5-??ILCRffq'
        '6R(Y<pNQ^#S}-R+6kYe!Ec)NFmpBtQVIo^96Ay_O^1oG1Jd~B`)S(BWEKNls3P}Dgy(ErhM7&U#%oZoTZ^_S`yXNqpHApW>OLMRM'
        'ynQ6h9jAAxHQ=0JT87B{Z|h%6)|Jn!s~=g{tXB<d*t%iev~F3qtvl9h*4@hKx-Rj*wX8Sk4Rz$kjqBnRJvT`Y$W+cO4ppst)_uqD'
        '1M35qzqxz#frrzNKbS4hOS=&Ia;Wq<?*{Q=q_8KnwI4aA9yuf_uJdD_6rJ!1XVzo!|8LeYd@{iBonZJR7`{8e@SR}z4lsNY44(kQ'
        'GcY^@!!s~E1H&^gJOjfsFgydpvjD?0FgydpGcY^@!!s~E1H&^gJOjfsFgydpGcY^@!!s~E1H&^gJOjfsFgydpGcY^@!!s~E1H&^g'
        'JOjfsFgydpGcY^@!!s~E1H&^gJOjfsFgydpGcY^@!!s~E1H&^gJOjfsFgydpGcY^@!!s~E1H&^gJOjfsFgydpGcY^@!!s~E1H&`P'
        '@Jup1lMK%!!!yb7Ofo!^49_IPGs*BwGCY$E&m_Y$$?!}vJd+I1B*U}idFv}2jQiZ<xNr}%M82U5-_S#RBaVLJ=;wPL{W!isA&+=d'
        'q~>F9h`k~9hS~t2Yg~kVGLj67p@-D^(1M8LCe6v_BlCZE<6+I(u>RBfuO`FU&bn|mKiH8-<S&SSB7@qqp%_C0+ncZNAh7*k=d}N8'
        'CTP{XL8~UHNNXZ!O@fNL0zqpMRMZ^^TKhmny`Z9QP*EqSC<!V$2r4=ND%u|iTK9p9`ane~P*E?as0UQk4Jzsa6?KA&IzUB9P*DO@'
        'q=AYwP>}{I(m+KTs7M19X`mtvRHT85G*FQSD$+nj8mLGE6=|R%4OFCoiZoD>1}f4(MH;9`0~KkYA`Miefr>Oxkp?Q#Kt&p;NCOpV'
        'pdt-aq=AYwP>}{I(m+KTs7M19X`mtvRHT85G*FQSD$+nj8mLGE6={-+G)YC8q#{jHktV4~lT@ThD$*nsX_AUGNky8ZB27|}CaFl1'
        'RHR8N(j*mWl8Uro(ApUXt?_F*eoe<gYwQiNHz<PEl!>se>In&r{Am#mTK}AX(kVj2GvatYDl|ONFeH4L6me%xEn7QRpQ2gMp=#w&'
        'rks76vH!v}Yc0G@IpOV+K-*Fb>3t!lC|>kxs0Zvh=%9A$RQ#X(Epg%T`!i;Ym@#a|a9qI<u3$vCLNeeA3AjQRT%kMQ3SDr8L|~ZJ'
        '1y@MI752jw_Q4fWaD^VYLKj@21Fn#OD;$L@9DyqwhAZ^L6%N4_4#E`<z!mlf<_7k`75d-`DY!x}T%iZ9&<$7Uf-7{w6*}MwNw`7+'
        'u3*3w47h>;S1{lT23)~_D;RJE1Fm4e6%4q70aq~K3I<%kfGZeq1p}^Nz!eO*f&o`B;0gv@!GJ3ma0LUdV89g&xPk#!FyIOXT)}`V'
        '7;psxu3*3w47h>;S1_b27}6CC=?aE)1w*=mAzi_cu3$)4Fr+IO(iIHp3WjtAL%M<?UBQs9U`SUmq$?QSP%`$0*c*QE-hfc@peMAW'
        'm199Av~otV^sZRUE><fiA7@3b$Z?iSy-T_N)qw{x=CnCOE4{*k#Q)$4n(enkMVkH2&SfWZ<;5z$UpXRISG5*mHXTl$e3UIbH6NLC'
        'W;v%?vGr4DA=UkWlu2#bjFPY(rxP6!l#<}dx_Hyh<DIUinGk<TigC+$H@T&cZhU3Dm)v-tTVLd)<b-|jJl^NVtO@a#q^HpHI3xNv'
        '=xbNxN(xif;RjqzHQ^Fm<k|cX5!sPCOQNJ7gxIh?KTPE4kft~*B})21o=w%|NBJ?3Y#jzsdJM$dbX)v5KLL`ao|Z(tt@`{VKLuhB'
        '#U#!+1;XEUyZj}78ZQaAzeMRNsZzJn9zVlh#*0RYSDf`SUP3L~;2J+GM>f>Ag!+{ox5&@A<D&%EqwtgU3vIE-U*YHRswJDA`#`;P'
        'sckm+1%45)@I>^LiSy6Xxr1%B%`fo*88V1m+_TGVx4{S9P^78r6g6bX(smsDGQWZ_$ho%{MVp5A{$AfTyZkD@hLEf2eh{^;Aw1hP'
        'O#C_@Lg?o_2Zr+`+}L%i{8c`TAah$iB5DpJDBX2@{06^?z}Nr8ToY{%%cthfo?+p)_-zE<+wL<_`!<60J;TcH@YgUfs6Ac7^nAU('
        '=Q#LXK7v6>OMNF=7{Op>&vEnD`5PEOg+GV4g^dw<7Vmv$`1qUrEez^f?qAW$TNn_2XV<{*@wYJ;^*yt6_eW*!eSiL#KY!FNdFYf`'
        'wX!F{Qa*-Zt-svD8FTWSCGR<(hM&b3FeFacXDo?Q5$=jQhB#|P)EpJ(j*0q~sIh=yv;W)`arPIg^VihpuZkL9hSgbbTxU(x`X*R!'
        'qxpL4qUJBXbvL(PcSF?vR@UEYz5b?X;a8#!NDQKpbRxO!cDB4NoeH!hnx@9m{mItaGa}m)=BUZEp4?umBim?IK%j=x!^!5_9&Nd8'
        '0gIYX-%mzc7;BRS0hNrTA11@?Si53Jz;{fgpCrB37WTxNxF|B1o=cL=C6CSYr@LfUTv@&4l~Bt95R9jnch~-E)Aj{aKuCYlZWL=f'
        'LLn{!K+<3C9Lsv!v53n9ob)%XAlldyMB>5$D*emmaBY5PxI~wDp{2hKLAUk%p%Xm@fazZmMo8!`#&n|NIe{s9&yN(7zbWf+I`txn'
        '(<u@qcUhcHxyv$s$l^3fafw)*-W74$?%TGD(|V%;?=Fbby8k|WZ^dc7Hlgr?5vS>zFWPrE7N?~+?K}suI2|rd`=6LtoZhZDEuXGo'
        '=lP1o=@!Ll=dBcr(|aLKQ(rp~jaQr|i8v7=PS^75#c4-YPAJ7`e|fk#Ev4y11993pV~H=5r!^3#{pU6or^C;W7N?`@sKx2#>V=Eb'
        '+pAkIPPbOyFHVyvxZQRZd@XH3oc6RtTAygFS#i3qJww?Z>2_$ckvLt~>c}=)Z6Hq9wLRK$+X`{I&caxmECj^qIy=^`*dgu9Hsuwk'
        'w;)dMx;2lGwFPn7wn;LUFiS?4q&(Cnv-JYs7R2d*Wm2Y=YTDGU+FxzL{z?EsOX74SinSe~*tR$wiDkX*Seg*0BN1)v38GMOIuh6B'
        'cZQ2}RTtW~;pn!WKXiU^dJE!oO_=_)1~Q%M@G$@>)4PGwMaj2(IP2AExdR7nC+h!@aiuGfu>LW>*qun^|G2Bchm41u4fevmU_4D<'
        'Fn;j9P8RSb<6L%edNw=R#?3AAKkXD~<%SmVw<YnnB|rFYOY(o&B|pL)wjQU4<H@J^%ZRWqBl_KMo8!r+_D(+0AUolba6I`GPd+`b'
        'lTRe!8vgtHgP(jd<dYCjJ}JJ8aGscW@~PFyr})c=c=G8*`!a$iOh@RcwFg%BU8b}rQr*d?`|kNPz4TB{Oj%CZ6T6hkQudTlzi;wM'
        'mPbuK$*Ct@oMDJ_QaGnSWb$cAlr}s0B+p$DXMdqSe@%7%s$C;`@=0AMdh)4pJ@w>Mtq+_@8g<>~CZ8JD4}2M6uSpN<-|bF5xh;{F'
        'pK_L&x7ePcY>(tayGc^!^%f?dnrM}Db~L=b$)|0%O}aTri1(9?EsV9vLQ|7ZN;@7&w9d{NA5q$goP6>;gSAf-+G#Ch^2uF8-CSqV'
        'gYade&TMY-DPWn@=ajoFdUx%wHf5irZwJB`$=yJ)wj&g_01x?n=UCR;iiIWu2+lXj))8&&38EG!pPIrYz1Bw723$=~K6%l(GdrqD'
        'on1#4KKbPRE&^RhQ%@3Oe~0`oB7LgEnRrU;9RjW)uyzp6RS(kP4i8vo_Ng)0=4YVX9l>5Wl{((PCswIrmHPSFzb96yzu)`!#GgpS'
        'Ds}5B^>FQ}iB;+*Rcd#+d8|^$`}e%SDz&3GhpW_-AEr`M*^>yB+9{7#shx8^jaBMBQK`3If9EQ-V*j3&RcgilJyA+&6DqZ0|DMLJ'
        'Hlb20_V3wl+Yu_YV*j3<TWD_op50KXp&D=1@87c<Dz(>I*#12cDs@O_Hm%P}vl09EG*qc~&3-c~b!{Q}4piz$6l*&|v2B$)63cp9'
        'u{5btM<UwT6GW>0d(^l#w}q?SI<QX#-cs$~6RlG3F*?QmJ&jaqSEJ@DyQ5O8Bz3<^y;b{8qL;p6$V|}|{gpHC<;r?7TQ>F5Z|BMr'
        'mOeF|eX3_C%DHD|Rq;cn7nMI`N*_=>n9i0;xrxZ1Fa1RmzZa1IldeR<`6K@Yea7M2u|NN(ltr8N=l@I`@l^iL>&|JzuKxMIt%3O3'
        'wiB^&KfnK6>i%?AwC3N5aZ_K@T0h1`A^N@?H#Mv0cL3c!QKLUnyYIB?Gkaur)Thxqt=8-F4ob`kgzTa3Aa%xdUX9&B>Wm@1+B#vC'
        'NRLx~gl;a;3ao;n&iM53l#S{LjZA$SIN>F<VpOTvmtMCK11~@4(W!gvE3xr<bZOm247~1dz^eC%*9C4L>VcXL?n6B&^OJtmioMw#'
        '+(xaZuXu4AwVuA}#ckAj`kEKFQS0sNUfhO6?rNS6ZbKq>bxjAiA(2PyCGJITYe+Zik=yyV>XF;|x9gGH`FHA(+xf56Be(PK)+4v`'
        'BlfA5*xgMP-tc30^WXGick|!!V|VlK`LVnCZ~L*k`S19#yZJlXuejf*b%f+EDDsyS`74V2RYm@qB7a?xzoE$AROD}k=ezs#))kym'
        '6&R|55mmvcs$fi2V5tfgR0T__f)!Q4s;Xd3Rj{rq*iaR0stUFg1@1nMbp^F;6Zz<K78=OFAnKzv85s075gG&n1IiEVj@Y%$(7+oQ'
        '9Eu1HWMI%22o1cgdP4&TX?<wm-NDcs7<i}Oy@7#u+T9x%9BB|5_`(=ZXy6ZIYN3HYkg0_R{#^leU=D@`Ixq)A109%yp@C}pS?3o*'
        'Ljw}k!$JcR!oxy?;IwZbFd*Dl<n?$01H$e6RH#2NaDSFwS4^u00t3Q5B(L8S7!Ypfr$+sO0pV8c<mL|yPP(CiKQK7qh6et?;J6za'
        '_ydDuZfM{S434^?fj=-f;)Vt_<ij$kQSK5J2x{EWAQ05Jp+O+1aYKVZP~(OMfuP0>4FW-p8yXOH!+u)a$&D6wi>mDg<=-hPkiVeF'
        'UsB|+DDqbo`D=>&bw&P$B7aknzZIS@e?GRp;FPMsP!)`*3Px20W2yp6Rj{BcSW*?Ns0vn91#7B;bydNJs$f%9u%#%FKc8D)5V2>)'
        '-}EFB`M;une!o}z^HooSZ7Ys>RF|;5E6$)S-n=5-ydvJbVlOwZ_=g_P<`sPIxn32VqGvW_-wL087&!!}SyZk5mDW7#gCmCkNs-&@'
        '*cGA5;fNuCGfe5TYab3-!HbX`-tFLUP+-Mx-3ndjTAXzs_F50$3S0-Ny}ra90ua`H0w)asPDZY(O^TNLY@|m;%P+Y@fG*qOL9AP;'
        't&k<Wgw|PmVz1Z@S@lYIouL&CS<bpcfDZdwsa<NdwrZ6E_g;I@LWoZ{90DZ85TM5%xDe_y)Xsp@&P7-t+%{^P!(Op1(A^{4HtNtJ'
        '0NuGkKkh5CHwOH;ugbyJB|q+KvZpVGeE)yJ9&%l+AqQ8Uw|nMF4LP_oDUf&Y%QfW6m5LHMt?M}?u%83VO5{VLjD`Sb!MYOpb%C9R'
        '0Gg`~O61q<A%I-n*J<}SA*TVrEkgd9)6RLj$FJA}fSZK;uG8Zk0)3yrJ}i*mAmqw#wFd=u2lripe1x#u3_l<&O5C(I>MR)llE5x;'
        '-x2v5-T;JL;=b)!4Mx4r1a=4c2w{I)Vy__|A?)wSUcYP)00{XAVQ=x9U0Mk>Y_Em#uY`Kyu7dJ^r%NlJoHb4UZ*v3rD~kM8MgE#1'
        'e_fHkp~&A<<Zp%N<9!%Xa7tBRs0v0@1*58hF;#)3Dp*hzEU5}sR0XT5f;Cmax~gD9Rj{cl*isZA9tbJ$eKhpKL<j!4!#FzlzD5Vc'
        ')9r~4=nWAT9gv0ZK04?G?yG_5p!SXpMh6`NJK?_kf<*@s`DJ?*@?l?e5L_ewqDKenwbG-=jiZA&I(V+50|<os?ZsLXa#7V_<y`2B'
        't-@@%!K$s7m8-TMef+3ywN_J$wX!5w=Km>`NaTMZ{wYPNl>3F1Fm>{tR40q(%&fR58`?}xWX%>t-fzvDrLu0&<xQGXxq>;VPt6u}'
        'XFJ}@4fRW@N~U5}GFByHRnn;O${EMsGG2enz~7pr8E3x2`aA1zezixq+1L56i3<LLrY>IX6aV~u%AUGdQj)@nbheP25*BS@38RO*'
        '<ms5RD9+BA#d6Lp>18Wh)&+Ix<EB1?CImAG#wc5+K0aR>s^+IUx3wO$(UeET8quG1VvVSC=C9{}PTP(DAx+-=OG+xhy1Oxi_0>mm'
        'Wr!f8^hhn!OH|%`x@ANE56npE_g}LB00'
    )
    assert isinstance(_MODEL_, _pydsdl_.UnionType)
